### ISSUE TITLE
Animations triggered at render time always run when outside the examples environment.

### ISSUE THREAD

**Issue by isglass** [bryntum/support#10100]
Here https://bryntum.com/products/calendar/docs/api/Calendar/widget/MonthView

**Comment by ExtAnimal** [comment]
We only don't see these visual glitches during bugbashes because we have several "cheat codes" in `shared.js` which makes our examples look good, but leaves customer apps open to visual glitches on startup.

`shared.js` sets `<body>` to `visibility:hidden` to hide any startup visuals. I suggest we remove that and *deal with any visual glitches*.

`shared.js` adds `b-notransition` to `<body>` and hide an `!important` rule in `shares.scss` to disable any startup animations. I suggest we remove that and *deal with any visual glitches*.

For a start in Widget.js:

<img width="1299" alt="Screenshot 2024-09-22 at 11 12 17" src="https://github.com/user-attachments/assets/d43cb675-1874-4540-9ac6-33454d56add0">
