### ISSUE TITLE
[ANGULAR] Events are not rendering when passing dependencies

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#10140]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=30528&start=10)

I am able to reproduce even with static data. Please find the attachment.
If I add dependencies, will not be able to see the tasks.
```javascript
<bryntum-scheduler-pro-project-model
    ...
    [dependencies]="projectProps.dependencies!">
</bryntum-scheduler-pro-project-model>
```
Added dropdown, where we can select the zoom level.
'Steps to reproduce:

Remove dependencies from the above piece of code.
Click on now line button and select for 2d or 3d from the dropdown (any zoomlevel). We can see the events.

If we add back the dependencies, will not be able to see the events.
[dependencies debug demo.zip](https://github.com/user-attachments/files/17190137/dependencies.debug.demo.zip)

**Comment by ghulamghousdev** [comment]
I have debugged the issue and it seems like this is not an issue. This is happening because when dependencies are used, tasks tend to schedule as early as possible. The tasks are rendered on the start date of the first task which is Wed Jan 03 2024 and the startDate of the last task is Fri Jan 12 2024. SchedulerPro has the start date set to `startDate : '2024-06-27' ` in config. So when they are changing the zoom level, the days being shown on the scheduler does not have any tasks. They just need to change the startdate of the schedulerPro.
