### ISSUE TITLE
React warning when using custom column renderer on React demo

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10158]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=30607&p=155391#p155391)

"I'm seeing "flushSync was called from inside a lifecycle method" warnings whenever I use a custom column "renderer".

I see it in the basic react example when I run it locally."

- Go to any React demo, and add a custom column renderer (as example)
```
{
                field : 'team',
                text :
                    'Team<div class="small-text">(inline JSX)</div>',
                htmlEncodeHeaderText : false,
                flex                 : 1,
                // Using simple inline JSX
                renderer             : ({ value }) => <b>{StringHelper.encodeHtml(value)}</b>
            }
```
- When running locally, the warning will appear

**Comment by ghulamghousdev** [comment]
Another report: https://forum.bryntum.com/viewtopic.php?p=155588#p155588

**Comment by Chochek** [comment]
Any updates on this?
I saw `#10260 - [React] flushSync was called from inside a lifecycle method runtime error` in the `v6.1.3` notes and hoped it was fixed but it's not. I'm still seeing the warnings when using custom renderers.

**Comment by jsakalos** [comment]
flushSync is only used when changing records. It is on purpose to force immediate UI updates. During the load of data or scrolling there are no warnings in version 6.1.3.

![flushSync](https://github.com/user-attachments/assets/d963a3d1-f3d0-4643-8c4a-3f5fd6ec13de)

**Comment by Chochek** [comment]
@jsakalos you're right, my bad. I checked again and the warning is gone

**Comment by tagnm** [comment]
I realise this issue is closed. But I just upgraded to v6.1.7

![Image](https://github.com/user-attachments/assets/26607e98-68d5-424e-800e-e20f17e4ffb4)

And I get the flush sync error as soon as I modify a record.

Here is a small example of code, that is triggered within a React useEffect.

![Image](https://github.com/user-attachments/assets/c1836116-670a-42ba-aa8c-8c758957e299)

Happy to open a new issue if that is more appropriate on the forum, but I came looking for this.
