### ISSUE TITLE
Remote filtering of the EventStore also filter the store locally

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#10417]
1. Use Scheduler php demo
2. Add `filterParamName : 'filter'` to eventStore config
3. Right-click timeaxis header and filter by name

**Comment by ExtAnimal** [comment]
It could be added that if remote filtering is enabled on a store, then adding local filters can be rejected (either with a throw, or ignore)

But it can be useful to, if you need to, apply some local filtering to a dataset that has been loaded using a remote filter. It's intentional that you are allowed to add local filtering.

**Comment by JockeLindberg** [comment]
It is GetEvents that applies store filters when getting events from resource.events
