### ISSUE TITLE
FinishDate badly calculated on negative Time zones (GMT -4)

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#10421]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=31279&p=159137#p159137)

Hello,

We continue with issues related with the negative Time zones, on the calculation of the FinishDate when changing the Duration (the same happens on the opposite).
We thought this issue was fixed with the issue #9798 (Non-working intervals are calculated incorrectly in certain time zone), but it is still happens on the Bryntum Gantt 6.1.3.

In resume, for the same StartDate and the same Duration, the FinishDate it is different, on different Time zones.
Attached to this Topic it is one video were is explained the situation and how to reproduce it on the Bryntum examples (Basic setup). Also attached are the files off the Bryntum examples changed to allow reproduce it.

Can you please take a look at it and solve it as soon as possible?

Thank you in advance.
Regards

**Comment by arcady-zherdev** [comment]
Hello,

Here is a quotation from [9798](https://github.com/bryntum/support/issues/9798) 
> The reason of the issue is too strict intervals that ignore DST change for that timezone.
> 
> ```js
>     "recurrentStartDate" : "on Fri at 0:00",
> ```
> 
> The rule doesn't match Friday 26 of April 2024 since DST was enabled on that date. So effectively there was `01:00` of the next day instead of `00:00`. And thus LaterJS doesn't match that date which results the calendars code confusing ..the number of interval opens and closes doesn't match.
> 
> I'll add a chapter on DST handling to the calendars guide and change the code to handle this a bit nicer. But there isn't much we can do. The intervals are just incorrect considering the timezone.

And here is the chapter that was added to the docs that explains what happened: https://bryntum.com/products/gantt/docs/guide/Gantt/basics/calendars#timezone-considerations

So the outcome of that ticket was the calendar intervals were configured incorrectly.
There was specified a date and time that did not exist in the used timezone.

Have you adjusted your calendars accordingly since then?

I see that the provided test case has:
```json
"recurrentEndDate" : "on Sun,Mon,Tue,Wed,Thu,Fri,Sat at 00:00"
``` 
In the previous ticket I found out that midnight didn't exist on a certain date due to the DST change.

Did you try adjusting the above rule accordingly to that finding? Like this for example:
```json
"recurrentEndDate" : "on Sun,Mon,Tue,Wed,Thu,Fri,Sat"
``` 

Best regards,
Arcady

**Comment by rfernandes-tk** [comment]
Hello,

After your explanation @arcady-zherdev we are able to use the negative timezones in better way.
For what we are to test until now, the issue does not happen anymore, but we will keep the tests on the next days/weeks.
If we found any issue on the tests, we will come back to this topic and discuss with you guys.

Thanks for your feedback and help.

Regards,
Ricardo Fernandes
