### ISSUE TITLE
Critical paths lines stay highlighted

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#1043]
Steps to reproduce:
1. open advanced demo
2. click "Critical paths" button
3. drag "Install Apache" task to start on Feb 18, 2019
4. the task is highlighted reddish as critical
5. click undo button (or drag the task back) to make the task non-critical
Result: dependencies are still highlighted as critical (while tasks are no longer critical)

**Comment by fabiojpoli** [comment]
@isglass I just checked that it is working on release and online, just on master is not working. But on both has this little problem that it doesnt change to red just part of the path when the record is critical:

![Screen Shot 2020-08-27 at 12 39 45](https://user-images.githubusercontent.com/663908/91470265-7f653680-e862-11ea-8c12-4f375ad18345.png)

I don't know if this is a bug because of this issue: https://github.com/bryntum/support/issues/1389

**Comment by fabiojpoli** [comment]
Was opened separated Issue about problem above about path partially gray: https://github.com/bryntum/support/issues/1433
