### ISSUE TITLE
Duplicated task when reordering while a filter exists

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1074]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14490&p=74042)

Steps to Reproduce

Go to the advanced demo: https://www.bryntum.com/examples/gantt/advanced/
Rename "Install Apache" to "foo Install Apache"
Rename "Setup load balancer" to "foo Setup load balancer"
Using the column header on the name column, add a filter for "foo". You should now see only 2 tasks within "Setup web server"
Drag "foo Setup load balancer" to the top of the list (above "foo Install Apache")

You'll notice that there are now 2 instances of "foo Setup load balancer" in the grid, both highlighted.

Not only does this appear to be a visual duplication but the taskStore seems to have gained a record after the drag (gantt.taskStore.allRecords.length is 41 before, 42 after).

**Comment by arcady-zherdev** [comment]
The reason of the issue is there are few places in our code that expect node `parentIndex` to be used as index for `children` array. But when we filter tree stores we replace node `children` array content ..but we don't update `parentIndex` respectively.

While the easiest workaround could be to update the index (which is actually found by the client) the `TreeNode` and `StoreFilter` classes logic looks dirty generally speaking.
Tree structure should stay intact when we filter data. So filtering the data should not cause:
1. changing of `children` array content
2. changing of nodes `parentIndex`, `previousSibling` and `nextSibling` fields

So we need to review the code places where we use `TreeNode` properties/methods and in case we expect to have filtered results need to switch to corresponding API (in case there is not such API we need to add it).

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2117
