### ISSUE TITLE
All day header out of sync with main schedule body after browser zoom

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1253]
<img width="758" alt="Screenshot 2020-07-28 at 14 23 20" src="https://user-images.githubusercontent.com/218570/88664812-eebdfe00-d0dd-11ea-8747-7584140a4ce1.png">

**Comment by ExtAnimal** [comment]
`calendar.modes.week.scrollable.hasScrollbar()` is somehow returning `false`, so the header row is no longer accounting for the visible vertical scrollbar in the detail view, so each column is out of step by `scrollbarWidth / 7` pixels.

Have to check how `hasScrollbar` functions when zoomed.

**Comment by ExtAnimal** [comment]
Needs:

```
    hasScrollbar(axis = 'y') {
        const { element } = this;

        if (element && DomHelper.scrollBarWidth) {
            const
                vertical   = axis === 'y',
                dimension  = vertical ? 'Width' : 'Height',
                clientSize = element[`client${dimension}`],
                borderSize = parseInt(DomHelper.getStyleValue(element, `border${vertical ? 'Left' : 'Top'}Width`)) + parseInt(DomHelper.getStyleValue(element, `border${vertical ? 'Right' : 'Bottom'}Width`)),
                difference = ((element[`offset${dimension}`] - borderSize) - clientSize) * window.devicePixelRatio; //<-

            // If the difference between the content width and the client width is
            // scrollBarWidth, then we have a scrollbar
            return Math.abs(difference - DomHelper.scrollBarWidth) < 2;
        }
    }
```

**Comment by ExtAnimal** [comment]
Hm no. That accounts for zooming happening *after* the scrollbar width has been read as 15. Zoom change should uncache scrollbarWidth so that it gets recalculated.

Unfortunately, there's no reliable way to detect zoom. So then `getScrollbarWidth` will have to cache the `devicePixelRatio` at the time of measuring, and then when called again, see if it's changed, and if so, uncache the `scrollbarWidth` so that it measures it at the new zoom setting.

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/1905
