### ISSUE TITLE
Recurrence dialog label text overlap

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1278]
https://www.bryntum.com/examples/calendar/recurrence/
double click Scrum event and open recurrence dialogue
Note the frequency label 
+ number input field is way too wide

<img width="461" alt="Screenshot 2020-08-01 at 13 01 37" src="https://user-images.githubusercontent.com/218570/89100453-5b473e80-d3f7-11ea-8e56-ed9e013d2dca.png">

Expected (position static for the weeks label material theme)
<img width="446" alt="Screenshot 2020-08-01 at 13 05 50" src="https://user-images.githubusercontent.com/218570/89100606-98f89700-d3f8-11ea-9a74-658e1c7454e6.png">

**Comment by dongryphon** [comment]
This problem is also present in the current [release of scheduler](https://www.bryntum.com/examples/scheduler/recurrence/) using the Material theme. It is a CSS issue regarding labels and absolute positioning

**Comment by dongryphon** [comment]
I'd suggest instead of using labels to get this effect (Stockholm theme):
![image](https://user-images.githubusercontent.com/722969/89185996-c6f8eb00-d560-11ea-9174-197a3013d0a1.png)

We could use an "overlay" config to achieve this (Material):
![image](https://user-images.githubusercontent.com/722969/89185868-8d27e480-d560-11ea-8131-456c37e86bee.png)

Stockholm:
![image](https://user-images.githubusercontent.com/722969/89186476-75049500-d561-11ea-9598-6fdbd69663fd.png)
