### ISSUE TITLE
Dependency creation tooltip styling broken in Safari

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1388]
Looks good in Chrome

<img width="1022" alt="Screenshot 2020-08-20 at 13 16 39" src="https://user-images.githubusercontent.com/5415653/90763716-78c94300-e2e7-11ea-9863-d744f5c10004.png">

**Comment by fabiojpoli** [comment]
Erro also on firefox just when start dragging.

**Comment by ExtAnimal** [comment]
This is a regression. Let's not patch on top of it. Let's dig back down to what broke it.

**Comment by ExtAnimal** [comment]
> Looks good in Chrome
> 

The header is broken.

**Comment by fabiojpoli** [comment]
@ExtAnimal I added this fix to :
```
.b-safari {
    .b-sch-dependency-creation-tooltip {
        .b-header-title {
            padding : 0.2em 0.6em;
        }
    }
}
```
Because on panel scss header has `padding : 0.2em 0`. But the firefox problem still is there.

Where you suggest I can look at?

**Comment by fabiojpoli** [comment]
Applied Nige’s suggestion instead of change paddings:
```
.b-panel-header {
    flex-shrink : 0;
}
```

But there is still a bug on firefox, we noticed there is a weird bug on firefox browser. Any change (or simply focus on css props) on css on the fly via debugger the problem is gone:
![Dec-10-2020 06-59-48](https://user-images.githubusercontent.com/663908/101769705-5edd8700-3ab5-11eb-8e60-bf9c8348181d.gif)
