### ISSUE TITLE
TaskEdit resets end time when user changes startDate

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1491]
1. Create new event using dnd
2. Edit end time
3. Edit `startDate`
end time will be changed/reset automatically. 

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=15212&p=76513)

**Comment by fabiojpoli** [comment]
Looks like think this is expected behavior.

User drag for 1 day duration new event. When he changes the start date, the end date will be changed to fit 1 day duration.

This validation is on scheduler edit class, but it check only on startDate event change, not on endDate event change. The change is available on current branch.

The user refer to scheduler-pro demo `recurring absences`  which doesn't exists, but based on his screenshot looks like the http://lh/bryntum-suite/SchedulerPro/examples-scheduler/recurrence/ demo , means is not a scheduler pro request, but scheduler (what are different on task editor feature, fully different classes).

To fix, the “feature” that change `endDate` automatically based on start date and duration was removed on Scheduler.

All tests available on branch with the fix/change for Scheduler, remaining the solution for SchedulerPro (test also ready).

**Comment by fabiojpoli** [comment]
> arcady:
> ok I think I recall that ticket ..for me the scenario that looks like a bug is:
> 1. user changes time part of endDate
> 2. changes startDate (not time part)
> Result: the time he entered resets back to its original value
> I undertsand that endDate could be  recalculated by startDate & duration but it's pretty clear that provided time is not taken into account ..it's just reset (edited) 
> 
> mats:
> Yes exactly, if we change end date we change the duration which the editor disregards later when start date’s modified
