### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#1523]
Calendars are giving me some strange results.  I have checked on your website and am getting the same issues.  Switching between calendars and back again affects the original duration.  I have created a video for you to see below;

https://www.loom.com/share/6cf9cea59c6a4e47a9ce60721abac2a5

Other issues i am getting on my calendars are;

1. I want to have a 1 day duration that starts and finishes on the same day, e.g Start at 8:00 & Finish at 17:00, this seems not possible. The only way to show a task starting & finishing on the same day is to create a milestone - but I need to have a 1 day task.  Is there a way to set this up?

2. Also see image below, can i stop this situation occurring - I clearly have a task running over 3 weeks but the duration is 5 days.  There is no effort applied or constraints - this should be 15 days??

3. A default setting of 20 working days per month, does that have an impact?  Generally there are more than that.

4. I have spent so much time trying to resolve these issues, can someone give me a demo please on how all this should be managed.  I would really appreciate it as it is very frustrating.

![image](https://user-images.githubusercontent.com/34025208/93328149-44c43d80-f813-11ea-9c02-165ac8f126bb.png)

**Comment by arcady-zherdev** [comment]
Regarding the video I could not reproduce this on our online demos. I see that the dataset differs from the one used by the demo out of the box so please provide more details on what other steps we need to do to see the issue.

> I want to have a 1 day duration that starts and finishes on the same day, e.g Start at 8:00 & Finish at 17:00, this seems not possible. The only way to show a task starting & finishing on the same day is to create a milestone - but I need to have a 1 day task. Is there a way to set this up?
1. You can easily check this even online. Open this demo for example: https://bryntum.com/examples/gantt/advanced/. And run this code in the browser console: 
```js
gantt.project.hoursPerDay = 8
gantt.project.calendar = 'business'
```
Details on calendars usage can be found in this guide: https://bryntum.com/docs/gantt/#Gantt/guides/basics/calendars.md#calendars-and-duration-values

> Also see image below, can i stop this situation occurring - I clearly have a task running over 3 weeks but the duration is 5 days. There is no effort applied or constraints - this should be 15 days??

The above link I've posted should help here as well. There are conversion ratios for duration units set on the project level and  `1 day` means `24 hours` by default. When you configure your project you change the ratios the way you expect the units to be.
Here is an example of response that sets an `8hrs/day` calendar to the project and defines units: `day` to mean `8 hrs`, `week` to `5 days` and `month` to `20 days`:
```json
{
  "success": true,
  "project": {
    "calendar": 777,
    "startDate": "2020-01-14",
    "hoursPerDay": 8,
    "daysPerWeek": 5,
    "daysPerMonth": 20
  },
  "calendars": {
    "rows": [
      {
        "id": 777,
        "name": "Default",
        "intervals": [
          {
            "recurrentStartDate": "every weekday at 12:00",
            "recurrentEndDate": "every weekday at 13:00",
            "isWorking": false
          },
          {
            "recurrentStartDate": "every weekday at 17:00",
            "recurrentEndDate": "every weekday at 08:00",
            "isWorking": false
          }
        ]
      }
    ...
}
```
> A default setting of 20 working days per month, does that have an impact? Generally there are more than that.

If you mean `daysPerMonth` config then it's just a conversion rate. It has impact when you for example define a task duration as `2 months`. Then the system uses that ratio to figure out what that exactly means (since a month can mean 30, 20 days or some other value depending on the use case).

> I have spent so much time trying to resolve these issues, can someone give me a demo please on how all this should be managed. I would really appreciate it as it is very frustrating.

I've posted above the response example defining `8hrs/day` project calendar and project setting that are typically used in this case.

Please let us know if you face other issues or have any questions.  It's probably better to use our forum for questions like these: https://www.bryntum.com/forum/ 
We observe it daily and try answering as quick as we can.
