### ISSUE TITLE
Create a demo showing drag events to grid

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1954]
Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=15976

As an opposite to drag from grid. Need to show users how to drag an event outside the scheduler and drop it on a custom element. The complexity is to support both event drag feature and drag to an outside element. Using another DragHelper creates an ambiguous behaviour, because 2 features will try to resolve drag action. Need to provide additional configuration to the EventDrag feature to support it. Must be solvable by providing dragHelperConfig and maybe overriding some methods.

**Comment by ExtAnimal** [comment]
We need to think about refactoring this dragging stuff to use the ne, simple and interoperable `Draggable` and `Droppable` mixins.

This is how the drag into Calendar from anywhere feature got written in very short time and completely integrates with Calendar. Because Calendar's Drag feature is a `Droppable` and knows how to drop records on itself.

All I had to do was implement a `Draggable` which knows how to "pick up" records (Very simple) and Calendar just accepted it, showed the correct drop indicators in all views automagically and dropped the record where required.

`Calendar/lib/Calendar/feature/ExternalEventSource.js` is 269 lines including full documentation.

SchedulerDrag needs to be refactored to use `Draggable` and `Droppable` and this will save a *lot* of time.

Comments @dongryphon ?
