### ISSUE TITLE
Adding manually scheduled parent task as predecessor from the cell editor fails

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2065]
https://www.bryntum.com/forum/viewtopic.php?p=80381#p80381

http://lh/bryntum-suite/gantt/examples/advanced/
`gantt.taskStore.getById(1000).manuallyScheduled = true`

Open cell editor in Predecessor column of 1.1 "Setup web server" record. Type in "1" to link it to 1 "Launch SaaS Product".
See the error:
```
Identifier.js:128 Uncaught (in promise) Error: Unknown identifier DependencyModelEx.$.fromEvent
    at throwUnknownIdentifier (Identifier.js:128)
    at EngineTransaction.get (Transaction.js:133)
    at EngineReplica.get (Graph.js:360)
    at TemplateClass.getFromGraph (ModelFieldAtom.js:56)
    at DependencyModelEx.get (Entity.js:151)
    at Dependencies.getTimeSpanRecordFromDependency (Dependencies.js:1041)
    at Dependencies.getRowRecordFromDependency (Dependencies.js:238)
    at Dependencies.js:1203
    at Array.forEach (<anonymous>)
    at Dependencies.addToGridCache (Dependencies.js:1196)
```

Basically, if you try to add this dependency from console, it fails with the same error (even if the parent task is not manually scheduled):
`gantt.dependencyStore.add({fromTask : 1000, toTask : 1})`

<img width="1120" alt="Снимок экрана 2020-12-09 в 17 37 15" src="https://user-images.githubusercontent.com/57486733/101643484-3ddd4d80-3a45-11eb-91ec-63a22ec2f23d.png">

**Comment by canonic-epicure** [comment]
The exception is caused by the fact, that newly added dependency is cyclic and thus its addition is rejected. The record is already in the store, but none of its atoms are in the graph (because of rejection).

The solution is to validate the dependency properly and if its invalid - do not add it to the store.

Current dependency validation works by calculating the start date of the `fromEvent`, however this does not take into account that manually scheduled tasks do not account the incoming dependencies.

Need to change the validation, instead of reading the start date, it can read some new lazy atom, which will read the same atom of every incoming (or outgoing) dependency. The value of that atom is not relevant, just the fact that it reads from every atom. If dependency is cyclic such reading will trigger a cycle.

**Comment by arcady-zherdev** [comment]
Ok so we detect cycles by calculating `startDate` and in this case it doesn't work since the calculation actually works ..but calculation of some other atom builds a cycle.

In the above case the cycle is built due to a parent-child relation (`earlyStartDateConstraintIntervals` calculation builds a cycle) so just iterating over incoming/outgoing links won't help.

And generally speaking making another synthetic atom will work only if it will reproduce all potentially failing atoms calculation logic.

As a quick solution we could simply replace usage of `startDate` atom with `earlyStartDateConstraintIntervals` one.

**Comment by arcady-zherdev** [comment]
Reading only `earlyStartDateConstraintIntervals` also doesn't help in 100% of cases ..ideally need to try calculating all the successor  atoms.

**Comment by arcady-zherdev** [comment]
Found one more problem in dependency column validation code.. reopening this issue.
