### ISSUE TITLE
Should not cause scroll after deleting an event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2114]
Compare Apple / Google Cal

**Comment by ExtAnimal** [comment]
This will need a reworking how how focus navigation is handled.

Focus is based solely on event elements being tabbable right now, so focus moves from the event being deleted to the next event is present, or the previous event in the view. If that is outside of the scrolling viewport, then it is brought into view so that the user does not lose context. So that focus does not in their eyes go to "nowhere".

What other calendars seem to do is move focus to the encapsulating time cell. So the _date_ becomes the navigation logical context, and the cell becomes the `activeItem` DOM element.

And then arrow keys seem to navigate between them.

The core `Core.helper.util.Navigator` class currently has two modes. One is where *it* is in control of focusing, and it listens for keyboard events and programatically pushes focus between items defined by an `itemSelector` (eg `.b-cal-event-wrap`)

The other mode, is where the items are naturally tabbable (See `itemsTabbable` in the Navigator class), and the Navigator just *listens* for focus moving naturally, and updates its internal state depending on reality.

We probably need it to be improved to blend both modes.

The `itemSelector` being `.b-cal-event-wrap, .b-calendar-cell[data-date]`, and somehow telling it that only when key event targets match `.b-calendar-cell[data-date]` should it perform its active focus-pushing mode.

What is returned as the logical active context needs to be defined too. It is either a date, or an event.

So you would have `activeContext` which is the logical, data-oriented info about the active location, and the `activeItem` which is the DOM element which is focused.

The conversion of the DOM active item into the logical `activeContext` is dependent upon the use case of the Navigator (It can be used by List, ChipView, DatePicker, Grid, Gantt and Calendar etc), so that would have to be a configured callback.
