### ISSUE TITLE
Unable to change to multiSelect on event editor

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#2141]
Related to: https://github.com/bryntum/support/issues/1851

Steps to reproduce:
- Change `resourceField` props on basic example:

```
new Calendar({
    ...
    features : {
        ...
        eventEdit : {
            ...
            items : {
                resourceField : {
                    type: 'combo',
                    label : 'Cal', // apply
                    multiSelect: true // does not apply
                }
            }
        }
    }
});
```

![Screen Shot 2020-12-18 at 3 35 27 PM](https://user-images.githubusercontent.com/663908/102659389-50433f80-4147-11eb-988f-5cfa61a3002e.png)

**Comment by ExtAnimal** [comment]
Is the calendar using multi assignment, or does its EventStore have the `usesSingleAssignment` flag set?

Because if so, it's entirely correct.

If the calendar does in fact use multi-assignment (And we need an example which shows that - I have the code), then it *automatically* uses multiselect.

There is no bug here, merely no example illustrating a multi assigned schedule.

**Comment by ExtAnimal** [comment]
Here's the example running:

![Screenshot 2021-01-12 at 12 16 30](https://user-images.githubusercontent.com/200516/104307816-a34eaf00-54c7-11eb-8bc3-32ab248cf430.png)

**Comment by matsbryntse** [comment]
Please see 'multiassign' demo where everything works well
