### ISSUE TITLE
Zooming should not change amount of view presets in Scheduler PresetStore

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#216]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=44&t=11732&p=68656#p68656
1. Go to http://lh/bryntum-suite/scheduler/examples/basic/
2. Run in console:
```
scheduler.presets.removeAll();

scheduler.presets.add([
    {
        base : 'hourAndDay',
        id   : 'MyHourAndDay'
    },
    {
        base : 'weekAndMonth',
        id   : 'MyWeekAndMonth'
    }
]);

scheduler.viewPreset = 'MyHourAndDay';
```
3. scheduler.presets.count // 2
4. Zoom In/Out
5. scheduler.presets.count // 3

**Comment by ExtAnimal** [comment]
The problem is in here in `TimelineZoomable.zoomToLevel`

```
// If we revert back to the original settings, and we had an original span
// then revert back to that span.
if (config.startDate && config.endDate && config.viewPreset && newPreset.equals(me.normalizePreset(config.viewPreset))) {
    span = {
        startDate : config.startDate,
        endDate   : config.endDate
    };
}
else {
    span = me.calculateOptimalDateRange(centerDate, panelSize, newPreset);
}
```

It attempts to see if the preset being set is the same as the one originally configured, and if so, using the same `startDate` and `endDate` as originally configured.

I think we agreed to remove that and *always* use `span = me.calculateOptimalDateRange(centerDate, panelSize, newPreset);`

The actual additional preset was because `normalizePreset` adds the resulting ViewPreset that it converts to into the Scheduler's `presets` store. Maybe that needs an extra boolean flag to say `skipAddToPresets`.

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/5b797de8-0f4a-4e6b-8c50-901959e7301e

**Comment by canonic-epicure** [comment]
Not reproducible anymore
