### ISSUE TITLE
Search in a tree grid by a full matched string produces Object object in cell content

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2293]
https://www.bryntum.com/forum/viewtopic.php?p=81962#p81962
https://www.bryntum.com/forum/viewtopic.php?f=43&t=16982&p=84370#p84370

http://lh/bryntum-suite/grid/examples/tree/

Grid/examples/tree/app.js
```
import '../../lib/Grid/feature/Search.js';
...
let tree = new TreeGrid({
...
    features : {
        search     : true,
```
Run in console:
`grid.features.search.search('Gate 5')`
See [Object Object]
<img width="957" alt="Снимок экрана 2021-01-27 в 15 05 10" src="https://user-images.githubusercontent.com/57486733/105988684-11db6180-60b1-11eb-8b86-695b6899afd3.png">

`grid.features.search.clear()`
Does not clear the search result

Now reload the page and collapse all records
`grid.features.search.search('Gate 5')`
Returns empty array. Expect records to be found. Also need to expand to those records: https://github.com/bryntum/support/issues/2287

**Comment by Yuvasee** [comment]
[object Object] issue appears only when we search for full item name. It we search for substring it's not highlighting matching substring, but at least not breaks UI. If you can start with just fixing critical [object Object] bug without making highlighting work, it will be already very important improvement for us. Because we can implement highlighting on our own, but I don't see acceptable way to override [object Object] bug.
