### ISSUE TITLE
Saving events when resource field is disabled resets assigned resource

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2340]
https://www.bryntum.com/forum/viewtopic.php?p=82390#p82390
Calendar/examples/basic/app.js
```
const calendar = new Calendar({
    features : {
        eventEdit : {
            items : {
                resourceField : null
            }
        }
    },
```
Edit an event, save, see it's green (there is no green resources)

Create a new event, see it is blue (Bryntum team resource). Enter a name and save. See it's green.
```
calendar.eventStore.last.resourceId // null, should be 'bryntum'
```
<img width="359" alt="Снимок экрана 2021-02-04 в 16 57 02" src="https://user-images.githubusercontent.com/57486733/106902882-5d71b900-670a-11eb-971c-485692777e15.png">
<img width="472" alt="Снимок экрана 2021-02-04 в 16 57 51" src="https://user-images.githubusercontent.com/57486733/106902893-5f3b7c80-670a-11eb-9f93-8fd6797dfbbc.png">
<img width="390" alt="Снимок экрана 2021-02-04 в 16 57 57" src="https://user-images.githubusercontent.com/57486733/106902890-5ea2e600-670a-11eb-961d-ea103c9a599e.png">

**Comment by ExtAnimal** [comment]
Bug is in Scheduler EventEdit code, but it happens because in Calendar, the "new" event record is added into the EventStore on a provisional bases (Clicking "Cancel" removes it because there's a flag that we're editing a newly created one)

The `finalize` method which is created as a closure in `save()` passes the `resourceRecords` to set into the "new" event based on the value of the `resourceField`. If there **is no** `resourceField`, that value is `[]`, so in `finalizeEventSave` that array is passed into `eventStore.assignEventToResource()`:

![Screenshot 2021-02-05 at 11 40 27](https://user-images.githubusercontent.com/200516/107023444-9196b980-679e-11eb-9f93-ef9eaefeaa85.png)

Maybe if there is no `resourceField`, `resourcerecords` could be set to `null`, and then in `finalizeEventSave`, that null value could be checked which means "Don't update the resources"

**Comment by ExtAnimal** [comment]
So maybe that code should be

```
            else if (resourceRecords?.length) {
                eventStore.assignEventToResource(eventRecord, resourceRecords, true);
            }
```
