### ISSUE TITLE
Multicombo box css is disturbed if it's not editable 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2355]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=16586&p=82509#p82509)

To reproduce, add this combo to calendar's sidebar 

```
    sidebar : {
        items : {
            calioStoreFilter : {
                multiSelect: true,
                type: 'combo',
                cls: 'b-stores-combo',
                weight: 3,
                valueField: 'id',
                displayField: 'name',
                label: 'Stores',
                width: '200px',
                items: [{id: 1, name: '24234234234'}, {id: 2, name: 'sdfds fsf sd fds fsdf sdf'}],
                editable: false
              }
        }
    }
```

Select both items from the list. There is a space above the selected values, but it should be fit to the top.
If `editable: false` commented - all looks as expected.

**Comment by ExtAnimal** [comment]
I think as is common, we are not seeing the full story.

It **appears** that the user's requirement is that the **chips** flow downwards as a column of fixed width blocks. The ChipView has `flex-direction: column; align-items: stretch`. We should offer that direction as a configurable option.

It's not a good solution to make the `<input>` use `display:none` because that kills focusability. It's the input field that you TAB onto.

When `editable : false`, the input is set to `min-width : 0` and has its left and right padding set to 0 because the assumption is that the ChipView flows in the `row` direction. The user's CSS has made it use `column`.

The solution is to add `min-height:0' to the rules and use `padding:0` instead of just squelching the left and right padding.

That way it will be tabbable, but will take up no space in the flex direction.

Also, I think he should use `labelPosition : 'above'` to move the label above, not changing the CSS of the outer element.
