### ISSUE TITLE
Scheduler 4.x is 2 times slower than Scheduler 3.x

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2358]
https://www.bryntum.com/forum/viewtopic.php?p=82560#p82560

Scheduler 4.x is a bit slower due to the Engine which is now part of it. Though Engine should calc nothing in Simple Scheduler and therefore shouldn't take x2 time to load data.

BigDataset demo[200 resources X 25 events]:

- 3.1.9 no deps
generate: 13 ms
data: 323 ms

- 3.1.9 with deps
generate: 10 ms
data: 1310 ms

- latest sources, no deps
generate: 117 ms
data: 563 ms

- latest sources with deps
generate: 113 ms
data: 741 ms

4.x is 2 times **slower** when no deps involved.
4.x is 2 times **faster** when there are dependencies.

**Comment by isglass** [comment]
Scheduler now always uses an AssignmentStore, which has big impact on this comparison:

Old demo has 200 resources + 200 x 25 events = 5200 records.

New demo has 200 resource + 200 x 25 events + 200 x 25 assignments = 10200 records.

Supporting both having and not having an AssignmentStore was becoming unmaintainable. Also many features did not take multi assignment into account. Thus we traded some performance for maintainability and improved features in 4.0.

With that said, I think I can shave perhaps 15% of the data phase for new Scheduler. Still slower than the old, but because of the assignment records we wont be able to match the old version any time soon.

**Comment by isglass** [comment]
Actually managed to improve it quite much. Not as fast as 3.0 but not far from. Data loading + rendering time in bigdataset demo with 1000 resource with 50 events each:

3.0 : 1100 ms
4.0 : 2150 ms
4.1 : 1250 ms
