### ISSUE TITLE
Improve calendar day view overlap handling to better handle wide layouts

### ISSUE THREAD

**Issue by dongryphon** [bryntum/support#2409]
From [forum](https://www.bryntum.com/forum/viewtopic.php?f=54&t=16690&p=83047#p83047) post:

![image](https://user-images.githubusercontent.com/722969/108363163-3dd29a00-71ba-11eb-881d-7e278ac05ed7.png)

and

![image](https://user-images.githubusercontent.com/722969/108363044-17146380-71ba-11eb-8485-c223896bab40.png)

**Comment by doonot** [comment]
Hi. This is getting a bigger issue for us now, please try to speed up the improvement, since a lot of customers are complaining because the calendar is not usable like this. I attached a new screenshot.

Thanks!

<img width="1006" alt="KEnEzqoCse-Fc8ZpZGfumu_t5peoqmVmvg" src="https://user-images.githubusercontent.com/767984/118941380-f0e59780-b951-11eb-88f3-398a2865aa81.png">

**Comment by dongryphon** [comment]
Hi @doonot - I am working this issue now. If it is not too much trouble, any example data sets you can provide would be helpful for my testing. Perhaps something like this to anonymize things from an eventStore:
```
JSON.stringify(eventStore.map(r => ({
    name: r.name.split('').map(c => /[\s,:-]/.test(c) ? c : 'x').join(''),
    startDate: +r.startDate/1000,
    endDate: +r.endDate/1000
})))
```
If there are recurrences I can expand the above to include those.
