### ISSUE TITLE
TaskEditor tab configuration in beforeTaskEditShow does not work correct

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2488]
https://www.bryntum.com/forum/viewtopic.php?p=83712#p83712

http://lh/bryntum-suite/gantt/examples/advanced/

Run in console:
```
gantt.on({
    beforeTaskEditShow({ editor }) {
        editor.widgetMap.notesTab.hidden = false;
    }
})
```
Edit a task. See, it makes the tab active and there is no content.

<img width="673" alt="Снимок экрана 2021-03-04 в 21 01 59" src="https://user-images.githubusercontent.com/57486733/110009391-002f4e80-7d2e-11eb-994b-b75374c69c63.png">

**Comment by ExtAnimal** [comment]
The TaskEditor has code which sets the heights of all the child items the first time the *generalTab* is shown.

It is never shown in this case, because that listener forces the *notesTab* to be shown first, so the tabs never get heighted.

*somebody* has to decide how the task editor is heighted.

We had decided that the general tab was going to do this job because we assumed that it was always shown.

We'll have to stop wimping out and have an opinion now.

**Comment by pmiklashevich** [comment]
@ExtAnimal Just created a new ticket about this specific problem based on user report https://github.com/bryntum/support/issues/2493
