### ISSUE TITLE
Panel items laid out using spacing by default

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2533]
A simple Panel with two checkboxes:
```
export default class SettingsPanel extends Panel {
    /**
     * Original class name getter. See Widget.$name docs for the details.
     * @return {string}
     */
    static get $name() {
        return 'SettingsPanel';
    }

    // Factoryable type name
    static get type() {
        return 'settingspanel';
    }

    static get configurable() {
        return {
            title : 'Settings',
            items : [
                {
                    type : 'checkbox',
                    text : 'Optimize by...'
                },
                {
                    type : 'checkbox',
                    text : 'Duration'
                }
            ]
        };
    }

    construct(config) {
        super.construct(config);

    }
};
```
![Screenshot 2021-03-21 at 09 38 04](https://user-images.githubusercontent.com/218570/111898899-30af0200-8a29-11eb-84fb-70bdee801592.png)

**Comment by ExtAnimal** [comment]
The issue is that since prehistory, the layout in a "container" (there wasn't a Container class back then) has been flexbox in the `row` direction.

This was probably done to aid in creation of the Scheduler EventEditor which needs two rows with 2 items on each row.

There's a `DateField` which is `flex-basis : 60%` and a `TimeField` which is `flex-basis : 40%` and so that makes up one line. All the other `Field`s are just `flex : 1`, and the Editor was heighted *by that content*, and so it all seemed to work.

But `flex-flow : row wrap` does seem to space items out:

![Screenshot 2021-03-22 at 14 09 38](https://user-images.githubusercontent.com/200516/111994611-dccb1880-8b0f-11eb-9f58-a72b0714f936.png)

I set the height of the Popup to 600 and the form items are spaced.

This is just a choice that was made.

To make the code in question in the ticket work, we can add

```
layoutStyle : {
    flex-direction : 'column'
}
```

Or, we could completely change how Container's default layout rules are, and have it default to `flex-flow : column`. That would of course break every container everywhere in the system and in all user apps.

**Comment by dongryphon** [comment]
Thanks Nige. In further discussion w/Nige, perhaps `align-content: start` may be good enough w/o changing the default to column.
