### ISSUE TITLE
Drag drop not finalized if eventStore data is cleared when dragging multiple events

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2774]
Related to https://github.com/bryntum/support/issues/1929

**Comment by cmanoliu** [comment]
Hello @matsbryntse, 

Unfortunately the fix is still **partial**. When dropping on the "ressources grid" the issue still exists :

![Bug Bryntum 4 1 3](https://user-images.githubusercontent.com/10958934/119158786-dea15180-ba56-11eb-9e4a-b7471f919389.gif)

We are stuck with the 3.1.9 since november 2020. All these drag/drop related issues are blocking us from upgrading...

Thank you for your support. 

Catalin
