### ISSUE TITLE
Draggable should not initiate drag on pointer down, but on first pointer move following pointer down

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3039]
Run this in basic sample and click an event:

`calendar.features.drag.on('catchall', console.log)`

Note the dragcancel event being fired.

Similar to how it's implemented in DragHelper.

```
onDragPointerDown(event) {
        let { dragging : drag } = this;

        // If a drag is ongoing already, finalize it and don't proceed with new drag (happens if user does pointerup
        // outside browser window). Also handles the edge case of trying to start a new drag while previous is awaiting
        // finalization, in which case it just bails out.
        if (!drag) {
            drag = this.setupDragContext(event);

            // If dragging is to begin, begin it.
            // The Context consults our beforeDrag handler, and if that succeeds, the Context
            // injects itself into here as our draggable.
            if (drag) {
                new DragContext(drag).begin();
            }
        }
        else if (!drag.isFinalizing) {
            drag.abort();
        }
    }
```

**Comment by dongryphon** [comment]
The code there creates the context in order to track the movement for a drag (like `DragHelper`). Inside `DragContext.begin()` it calls a method on the source (`beforeDrag`) to gather details of the event target for the potential drag but it does not call `startDrag` until/unless a subsequent move is "significant" in DragContext.move:

```
        if (target && target.nodeType === Node.ELEMENT_NODE) {
            if (significant && !me.started) {
                me.event = event;

                // triggers beforeDragStart, dragStart. returning false from beforeDragStart aborts drag
                if (me.start() === false) {
                    me.abort();
                    return;
                }
            }
```

Is there some issue related to a `beforeDrag` method this sequence is causing? It is always possible that a Draggable-derived class implements too much in `beforeDrag` that should have waited for `dragStart`.

**Comment by bmblb** [comment]
I remember stumbling on this when I was working on scroll manager refactoring. If I recall correctly negative implication of this greedy drag was causing scroll jumping. Maybe that's why I added a flag to skip restoring focus in this method: https://github.com/bryntum/bryntum-suite/pull/3548/files#diff-e0a3ec38f6bdedb1b3392d82d9b6e8be2f413357b80f90bf8c1d7f749e765a53 See modified `me.refocus?.(false);` call.
When me and @ExtAnimal were looking at that we thought drag context was created too soon but it was too much of a deal to fix in the same PR.
So there you go :)

**Comment by dongryphon** [comment]
In the PR I've added more docs explaining the transition from INIT state of the `DragContext` to the START state (which occurs when the mouse moves 5px by default) as well as a test suite for `Draggable` and `Droppable`. There's room for more tests as always, but there is a good start there now.
