### ISSUE TITLE
Combining Search Filter with any other filter causes a crash

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3105]
Reproduced executing the steps in the post.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=17945&p=88847#p88847)

Hi, 

We utilize the Search filter in the Toolbar along with our existing filters. But in the advanced example, toolbar search contains 'replace: true' which removes existing filters. On removing this line, we get an error if we utilize this filter along with other filters.

Steps:
Go to advanced example (https://bryntum.com/examples/gantt/advanced/)
In code, remove replace: true in onFilterChange()
Right click duration column -> Edit Filter -> Equals = 2 days
Search any task in Toolbar search, it will cause a crash.

![filterReplaceError.png](https://www.bryntum.com/forum/download/file.php?id=13678)

Any thoughts / suggestions?

Thanks,
Nagaraju
![filterReplaceError.png](https://www.bryntum.com/forum/download/file.php?id=13678)

**Comment by arcady-zherdev** [comment]
https://www.bryntum.com/docs/gantt/#Core/data/mixin/StoreFilter#function-filter

Checking the docs it looks like this is by design actually.
That nested `filters` property is made specially for cases when `replace` flag is provided:

So if you want to add a filter instead of replacing existing ones it should look like this for example (I've modified the advanced demo code):
```js
            this.gantt.taskStore.filter(task => task.name && task.name.match(new RegExp(value, 'i')));
```
