### ISSUE TITLE
Adding filters shows wrong date filter value

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3145]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=18053&p=89373#p89373)

Hello !

You can reproduce the bug here https://www.bryntum.com/examples/grid/filterbar/, you just need to add this :

```
grid.store.addFilter({
  property: "start",
  value: new Date(2019, 0, 26)
});

grid.store.filter();
```

addFilter() works correctly but the value "01/26/2019" becomes "01/01/100" after filter(). Is there a workaround or a quick fix for this issue ?

Regards,
artbil

--

also note field value in the column header, it shows incorrect string unless you pick value from the date picker

**Comment by ExtAnimal** [comment]
This is a general problem with Javascript. There's no Date literal, so you can't specify a date as input for any Javascript code unless you either pass `new Date(...)`, or you have a convention in the code where you *tell it* that what you are sending should be parsed (somehow) into a Date..

Now it works the first time now because of a recursion bug.

The filter at first filters all out because the values do *not* match the string. `'01/25/2019'`

When the filter fires its "after" event, the FilterBar hooks that and finds the columns for the filters and updates their value to keep them in sync with how the store is filtered. It sets the value of the `DateField`. YY/MM/DD is the default, so the set value works.

The `DateField` fires its `change` event. This is how Filterbar works. It listens to `change` events on its field to perform filtering.

This filters the store **__for a second time__** by the `toString` value of the date which works.

```
                store.filter({
                    columnOwned : true,
                    property    : field.name,
                    ...me.parseFilterValue(value)
                });
```

Because `parseFilterValue` returns the stringified value instead of the raw `Date` `'Sat Jan 26 2019 00:00:00 GMT+0100 (Central European Standard Time)'`. and not the raw Date which it should.

So the store gets filtered a **SECOND** time. This time correctly.

But when we the call `filter()`, it fires the filter "after" event, and the FilterBar tries to set the `DateField`'s value to that stringifed version of the date which doesn't parse correctly with MM/DD/YYY, so the field flips to that incorrect value. It fires a change event and round we go again which filters all records out.

So first we need to remove the recursion. If the FilterBar is in the phase where it's responding to a filter event and changing the input fields, it should not during that phase, respond to its field change events.

`parseFilterValue` should be

```
    parseFilterValue(value) {
        if (Array.isArray(value) || ObjectHelper.isDate(value)) {
            return {
                value
            };
        }

        const match = String(value).match(this.filterParseRegExp);

        return {
            operator : match[1] || '*',
            value    : match[2]
        };
    }
```

`updateColumnFields` should be

```
    updateColumnFilterFields() {
        const
            me = this,
            {
                columns,
                store
            }  = me.grid;

        let field, filter;

        // During this phase we should not respond to field change events
        me.updatingColumnFilterFields = true;

        for (const column of columns.visibleColumns) {
            field = me.getColumnFilterField(column);
            if (field) {
                filter = store.filters.getBy('property', column.field);
                if (filter) {
                    // For filtering functions we keep what user typed into the field, we cannot construct a filter
                    // string from them
                    if (!filter._filterBy) {
                        field.value = me.buildFilterString(filter);
                    }
                    else {
                        field.value = filter.value;
                    }
                }
                // No filter, clear field
                else {
                    field.value = '';
                }
            }
        }
        me.updatingColumnFilterFields = false;
    }
```

and `onColumnFilterFieldsChanged` should be

```
    onColumnFilterFieldChange({ source : field, value }) {
        const
            me         = this,
            { store }  = me.grid;

        // Don't respond if we set the value in response to a filter
        if (!me.updatingColumnFilterFields) {
            // we don't want to hear back store "filter" event
            // so we suspend store tracking
            me.suspendStoreTracking();

            if (value == null || value === '' || Array.isArray(value) && value.length === 0) {
                // remove filter if setting to empty
                store.removeFilter(field.name);
            }
            else {
                store.filter({
                    columnOwned : true,
                    property    : field.name,
                    ...me.parseFilterValue(value)
                });
            }

            me.resumeStoreTracking();
        }
    }
```

But we still have the problem where the initial filter doesn't work.

I don't think we can expect `Store.filter` to understand that the test value coming in is in the format of some `DateField` that might or might not be in a UI which is attached to it (Stores may be shared and must not know about UIs).

I think the best we can do is use the referenced field's own conversion, so StoreFilter needs

```
    addFilter(filter, silent = false) {
        //<debug>
        if (filter._filterBy && this.remoteFilter) {
            throw new Error('Cannot filter with a function if remote filtering is being used');
        }
        //</debug>

        const modelField = this.modelClass.fieldMap[filter.property];

        // If we found a defined field, ensure the incoming test value is <-----Fix
        // converted into the correct type.
        if (modelField?.convert) {
            filter.value = modelField.convert(filter.value);
        }

        filter = filter instanceof Filter ? filter : new Filter(filter);

        // We want notification upon change of field, value or operator
        filter.owner = this;

        // Collection will replace any already existing filter on the field, unless it has id specified
        this.filters.add(filter);

        if (!silent) {
            this.filter();
        }
        return filter;
```

And then they could do

```
grid.store.filter({
    property  : "start",
    value     : "2019-01-26" //<-- the format that the modelClass's start field uses.
});
```
