### ISSUE TITLE
Task with percentDone > 0 should be treated as manually scheduled and not be impacted by predecessor being rescheduled

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#3211]
Requested here: https://www.bryntum.com/forum/viewtopic.php?f=53&t=18274&p=90377

Task having `percentDone` > 0 should not recalculate their positions in this mode.

**Comment by scscott12** [comment]
To add a bit more. The logic should be retained. If the predecessor task(s) are not complete but the logic states that the predecessor(s) have to start/complete before the successor activity the activity with percentDone >0 should have its finish date pushed out (taking into account the tasks remaining duration) so that the logic stays intact.
![image](https://user-images.githubusercontent.com/35305550/126801595-2692fd2b-b19f-4d55-9d3c-0b54776d95e7.png)
Activity C has percentDone > 0 but the predecessor task, logic is FS, is not complete. Activity C has an end date 2 days after Activity B.

**Comment by arcady-zherdev** [comment]
> To add a bit more. The logic should be retained. If the predecessor task(s) are not complete but the logic states that the predecessor(s) have to start/complete before the successor activity the activity with percentDone >0 should have its finish date pushed out (taking into account the tasks remaining duration) so that the logic stays intact. ![image](https://user-images.githubusercontent.com/35305550/126801595-2692fd2b-b19f-4d55-9d3c-0b54776d95e7.png) Activity C has percentDone > 0 but the predecessor task, logic is FS, is not complete. Activity C has an end date 2 days after Activity B.

Yes but that's a much more complex feature. The current code is way far from it at the moment. I think for the first version it's ok to implement the behavior from this ticket description.
And for your request I've made a separate ticket: https://github.com/bryntum/support/issues/9365

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?t=29475
