### ISSUE TITLE
Implement configurable data relations between models.

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3222]
Requested here: 

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=18294&p=90466#p90466)

Hi team,
I have data as below:

```
  "newarray": [
                  {
                    "id": 1,
                    "from": "PHO",
                    "to": "MNL",
                  },
                  {
                    "id": 2,
                    "from": "MNL",
                    "to": "AHM"
                  }
                ]       
         
```
![MicrosoftTeams-image (20).png](https://www.bryntum.com/forum/download/file.php?id=14029)

How i can create a store just like baselines in the above screenshot
![MicrosoftTeams-image (20).png](https://www.bryntum.com/forum/download/file.php?id=14029)

**Comment by isglass** [comment]
There is a relation system but it is fully private, ticket should probably be repurposed to document it and make it public

**Comment by pmiklashevych** [comment]
+1 for making it public

**Comment by pmiklashevych** [comment]
Please implement this for Model. I have lots of related models. For example, I have Groups store, which looks like:

```
// Groups Store
[{
  id : 1,
  title : 'Forwards',
  // Players Store
  players: [
    { id : 1, name : 'Kylian Mbappe' } ,
    { id : 2, name : 'Lionel Messi' },
    { id : 3, name : 'Neymar' }
  ],
}]
```
So it's obvious there is a Players store holding info of all players, and there is a Groups store, which organises players in some groups, for example forwards. Every group has "players" field which would be nice to have turned into a Store of Records instead of simple array of objects.
