### ISSUE TITLE
Support for typing free text into combo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3249]
Add it to its store if not present already

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=18277&p=90766#p90766)

i had some free text combos implemented this way:

viewtopic.php?f=43&t=17163&p=85878&hilit=free+text+combo#p85878

These aren't working in 4.2.1 and 4.2.2.  You type a bit, click on the list item and tab and it will more often than not leave with the characters you typed instead of the list item you selected.

**Comment by gregcault** [comment]
The basic workflow I would like is
Precondition: I already have a combo with a drop down list of id/display value pairs
1) Edit cell and be able to type a new value into the combo.  
2) For AJAX this value is sent as part of the record update somehow signifying it is a new value
3) After the record is committed to the store or sent to the server for AJAX the value is inserted into the column combo which filters the table, and will also be in the combo for editing the cell.

**Comment by ExtAnimal** [comment]
A very old request: https://app.assembla.com/spaces/bryntum/tickets/8913

# Allow adding new items to combos

Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=11679#p62410

If input value doesn't match a record in the list pressing ENTER should add a new item to the combo.
Need to provide `allowNew` config and `delimiter` config, so that its handling can hook the delimiter character as well as `ENTER`.

### A comment from @NigeWhite
Combo's `onKeyDown` would grow somewhat. It would have to look at the `keyEvent`, and if it was `ENTER` or the configured delimiter character (Probably `','`), _and_ if `me.allowNew`, then it should take the input field value, and create a `new me.store.modelClass({[me.valueField] : inputValue, [me.displayField} : inputValue})`. It should then probably fire that new record out in an event like `'newRecordCreated'`, so that developers could somehow add stuff to new records. Then add that new record to `me.store`, and `select` it. That should be it.

Work on the delimiter key is started in a stash named "Combo multiSelectKey"
