### ISSUE TITLE
dataChange event does not fire on SchedulerPro

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3428]
Reproducible on online-demo:
![datachange-event](https://user-images.githubusercontent.com/204844/133775107-6f2b834e-381c-40b9-b94f-8391e8d0d08a.gif)

**Comment by isglass** [comment]
Caused by different mixin order in Scheduler & Pros ProjectModel. 

Rearranging pros to look like this fixes it:

```
export default class ProjectModel extends ProjectCrudManager(ProjectModelMixin(SchedulerProProjectMixin)) {
```

But that might very well break something else. I would first try it and check tests, if they fail add a conditional super call to `AbstractProjectMixin#attachStore` (will have a super in pro but not in normal scheduler I think)
