### ISSUE TITLE
Extra scrollbar space when resizing partner panels

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3495]
Reproducible on resourcehistogram demo: schedulerpro/examples/resourcehistogram/

If you slowly drag splitter up, when bottom panel stops overflowing time axis header get resized seemingly to leave room for a scrollbar

https://user-images.githubusercontent.com/45400762/135822711-85cab030-d206-48ae-b3ca-3d763e33cc54.mp4

**Comment by jsakalos** [comment]
This issue is most likely related: https://www.bryntum.com/forum/viewtopic.php?p=96971#p96971

Comments from the chat with @ExtAnimal:

![1CEF7FDF-9492-4A6C-89DC-EF25F0B55B66](https://user-images.githubusercontent.com/204844/143227879-ab4feebb-00a5-4d05-bb94-8a6135290f8a.jpeg)


Scroller has an overflowchange event now that we can tell when a scrollbar appears or disappears in any dimensoipn
So we can listen for that
And add/remove the CSS class which shows/hides that padding
`b-show-yscroll-padding` needs to be added to the <header> when it has to show a scrollbar sized gap
I think whoever fixes it should look at both
