### ISSUE TITLE
Opened dropdown list not re-positioned when scroll the entire app

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3552]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19083&p=94393#p94393)

Hello

We've spotted a little problem with the LWC version of the Grid - namely when one is scrolling through options in a dropdown column. We've noticed that if you open the dropdown and then scroll down not through the dropdown options but through the grid itself, then the dropdown says open and hanging and looks very odd. I've attached a video below. I've not been yet able to replicate it on the Bryntum demos, but I have replicated it on very simple LWC demos. 

I've attached the code for the column in the video below. As you can see, its fairly simple. 

```
export const COLUMNS = [
    {
        text: 'City',
        field: 'city',
        flex: 1,
        editor: {
            type: 'dropdown',
            items: [
                'Stockholm',
                'Moscow',
                'Paris',
                'Washington',
                'San Francisco',
                'New York',
                'Barcelona',
                'Dubai',
                'a',
                'b',
                'c',
                'd',
                'e',
                'f',
                'g'
            ],
        },
    },
];


```

**Comment by bmblb** [comment]
This issue is blocking: #3941

**Comment by taauntik** [comment]
A user asked for the fix [here](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19083&p=108160#p108160)

**Comment by bmblb** [comment]
When realigning floating elements in WC we use two listeners - one on the document and another one on the fragment (both are returned by the `element.getRootNode()`). One problem is that document fragment in salesforce does not allow to add listeners in the capturing phase. So instead we use first child (there is supposed to be only one). Another part is listening to the document scroll to reposition floating element on page scroll.

Inner LWC scroll works just fine. But when we scroll the document we cannot hide floating element if its align target is hidden - because we don't know if it is hidden. LWC doesn't know own position on the page. We could check scroll position, but there may be intermediary scrollable elements to which we cannot have access for security reasons.

So current behavior is:
1. If LWC element is scrolled and align target is out the LWC view, floating element is hidden
2. If page is scrolled, floating element will remain there until user clicks somewhere on the page because LWC doesn't know it is not in the view anymore
