### ISSUE TITLE
No 'change' event fired after indent operation

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#367]
Advanced sample:
`gantt.taskStore.on('change', console.log)
`
Then indent a task

https://bryntum.com/forum/viewtopic.php?f=52&t=13442

**Comment by ExtAnimal** [comment]
A `change` event _is_ fired when a child node is inserted. But events are suspended inside a propagate because many atomic changes may ensue from one change, and having each one update the UI would harm performance.

We should probably involve @arcady-zherdev .

https://github.com/bryntum/bryntum-suite/blob/master/Gantt/lib/Gantt/data/TaskStore.js#L77

(I don't know why `TaskStore` has a property `taskStore` which refers to itself though!)

This relates to this ticket which we need to discuss and decide on any plan to make events "filterable": https://github.com/bryntum/bryntum-suite/issues/7

Some events need to be held back from the UI, while still being available for data purposes.

To fix this though, `TaskStore` could fire a new `indent` event at the end of that method.
