### ISSUE TITLE
Collapsed Panel fixes its container's height

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#3674]
When that grid panel is collapsed, the Calendar does not shrink in height, flexing the week rows down:

![Screenshot 2021-11-05 at 14 28 48](https://user-images.githubusercontent.com/200516/140517728-1dba2a3f-07ca-4300-8a58-3c9f316e0436.png)

**Comment by dongryphon** [comment]
We'll need to look over this. I suspect the issue comes down to the grid having an auto-height. When it collapses there is nothing to "support" a natural size anymore, and so the panel collapser preserves the original size. If that is what you are describing, the best answer is to constrain the height of these two items to the viewport.

**Comment by dongryphon** [comment]
The issue described here requires a browser resize to observe.

It is caused by the cross-axis of the collapse (in this case the vertical axis aka height since the panel was collapsed horizontally) being propped up. This is needed if the panel is absolute positioned (as in the unit test in some cases) but is not needed in most cases because the container will typically provide size for the cross-axis.
