### ISSUE TITLE
Support Salesforce Winter 22 release 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3680]
Here is some tips from our user who investigated this and found some issues in our code.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19341&p=95607#p95607)

Hej!

Salesforce is working on a new security layer to replace the Locker Service named "Lightning Web Security" and it is now in beta as of Winter'22 release.

This new technology brings some long awaited features to Lightning web components, but it is not without fault.

Whilst testing integration with third party libraries I have discovered the following issues that affect your component bundle functionality:

The global window reference is null, which passes the (typeof !== 'undefined') check in BrowserHelper.isBrowserEnv but causes issues everywhere else. Solution: inject const window = globalThis; into the bundle file at compile time.

The Core/helper/AjaxHelper calls BrowserHelper.queryString?.__resourceRoot which creates new URL from window.location.href which throws because href is undefined. Solution: always return empty object from queryString because AjaxHelper is useless in LWC environment anyway.

The Core/helper/EventHelper throws in the fixEvent() method attempting to read the type property of the event parameter. Solution: remove the following line from EventHelperOverride: event = Object.create(event);. Looks like LWS is very particular about the Event object.

After Grid/view/SubGrid builds grid rows in onAddRow() and inserts them to the DOM, all data- attributes are missing from grid cells, which prevents column resize and other cell level manipulation. There is no solution for this problem at the moment. I have created an isolated (not using Bryntum code) reproduction of this issue and reported it to the PM for Lightning Web Security.

I hope you find this information useful.

**Comment by bmblb** [comment]
window is not supported by LWS, globalThis - by Locker Service. `self` is supported, need to add this to the bundle:
```
const [window, globalThis] = [self, self];
```

**Comment by amurashinffdc** [comment]
I was testing a recent Nightly code with Lightning Web Security enabled and found two blocking issues which throw on script load.

## Problem 1

The `MessageDialogConstructor` at some point calls `DomHelper.scrollBarWidth()` which adds a `div` to `document.body` using `DomHelper.createElement()` which calls `parent.insertBefore()`. And LWS isn't particularly happy about it.

```
Error: Lightning Web Security: Cannot insert child DIV into BODY,
    at HTMLBodyElement.insertBefore$LWS (aura_proddebug.js:16943:17)
    at HTMLBodyElement.instrumentedDistortionWrapper$LWS (aura_proddebug.js:18739:16)
    at Object.apply (aura_proddebug.js:13006:16)
    at aura_proddebug.js:20223:15
    at BoundaryProxyHandler$LWS.eval [as apply] (eval at createConnector$LWS (aura_proddebug.js:20701:33), <anonymous>:479:23)
    at Function.createElement (all.lwc.js:14578:24)
    at Function.get scrollBarWidth [as scrollBarWidth] (all.lwc.js:15577:92)
    at Function.get outerCls [as outerCls] (all.lwc.js:32599:27)
    at Tool.updateParent (all.lwc.js:29011:72)
    at Tool.set (all.lwc.js:2599:40)
```

I created this override for `DomHelper.createElement()` to work around the issue:

```js
class DomHelperOverride {
    static get target() {
        return {
            class : DomHelper
        };
    }

    static createElement(config = {}, options) {
        if (config.parent === document.body) {
            // Lightning Web Security does not allow adding elements to document.body,
            // so we hack around this restriction and instead use the LEX viewport div.
            // However, the Locker restricts access to the document content but allows
            // appending elements to body, so we fallback to it.
            config.parent = document.querySelector('div[class="viewport"]') || document.body;
        }

        return this._overridden.createElement.call(this, config, options);
    }
}
```

What happens there is in Locker environment, the `querySelector` call will return `null` and the `document.body` will be used as `parent` element (which works fine in Locker), but in LWS environment we attach to the viewport `div` (I know, this is not the most reliable solution as it relies on specific markup). Once the child element is created, the `getScrollBarWidth` method forces it into `document.body`, which LWS seems to be totally fine with:

```js
if (element.parentNode !== doc.body) {
    doc.body.appendChild(element);
}
```

## Problem 2

The already overridden `EventHelper.fixEvent()` method wraps the original Proxy event object to be able to define custom properties on it:

```js
static fixEvent(event) {
    event = Object.create(event);

    event = this._overridden.fixEvent.call(this, event);

    // ...
}
```

This, however, upsets LWS when the base object's property is accessed because it does not recognise the value of `this` and cannot resolve the original `Event` instance, so it throws "Illegal invocation" error.

I believe this is due to the [membrane](https://github.com/salesforce/near-membrane) implementation which uses a `WeakMap` to reverse lookup protected objects from proxies, so when we try to read `event.type` the `type` property getter uses value of `this` as a key which no longer matches the original Proxy stored in the map. My override works around this problem by delegating property access to the base object.

```js
const copyPropertyNames = [
    // Event
    'bubbles', 'composed', 'cancelable',
    'type', 'target', 'currentTarget', 'path',
    'timeStamp', 'defaultPrevented',
    'isTrusted', 'eventPhase',
    // UIEvent
    'detail', 'view',
    'layerX', 'layerY',
    // MouseEvent
    'button', 'buttons',
    'clientX', 'clientY',
    'movementX', 'movementY',
    'offsetX', 'offsetY',
    'pageX', 'pageY',
    'screenX', 'screenY',
    'x', 'y',
    'region',
    'relatedTarget',
    // KeyboardEvent
    'code', 'key', 'repeat', 'location',
    'metaKey', 'altKey', 'ctrlKey', 'shiftKey',
    'isComposing',
    // TouchEvent
    'touches', 'changedTouches', 'targetTouches',
    // TransitionEvent
    'propertyName',
    // PointerEvent
    'tiltX', 'tiltY', 'twist',
    'height', 'width',
    'pressure', 'tangentialPressure',
    'pointerId', 'pointerType',
    'isPrimary',
];

const copyFunctionNames = [
    // Event
    'composedPath',
    'preventDefault',
    'stopImmediatePropagation',
    'stopPropagation',
    // MouseEvent, KeyboardEvent
    'getModifierState',
    // PointerEvent
    'getCoalescedEvents',
]

const createPropertyAccessor = function (propertyName) {
    return function () {
        return Object.getPrototypeOf(this)[propertyName];
    }
};

const createFunctionAccessor = function (propertyName) {
    return function () {
        return () => Object.getPrototypeOf(this)[propertyName]();
    }
};

const wrap = (event) => {
    // Locker Service returns secure object, which is in fact object with null prototype and not Event instance
    // We wrap that secure event with another object to allow redefining properties
    const wrapper = Object.create(event);

    // Accessing original event's properties or methods via the wrapper object
    // under Lightning Web Security will throw the "Illegal invocation" error,
    // so we redefine them as own properties acting as proxies to the original.
    const propertyDescriptors = {};

    copyPropertyNames.forEach((name) => {
        if (name in event) {
            propertyDescriptors[name] = {
                get          : createPropertyAccessor(name),
                configurable : true
            };
        }
    });

    copyFunctionNames.forEach((name) => {
        if (name in event) {
            propertyDescriptors[name] = {
                get          : createFunctionAccessor(name),
                configurable : true
            };
        }
    });

    Object.defineProperties(wrapper, propertyDescriptors);

    return wrapper;
}

class EventHelperOverride {
    static target = { class : EventHelper }

    static fixEvent(event) {
        event = this._overridden.fixEvent.call(this, wrap(event));

        // ...
    }
}
```

I hope you will find this information useful.

**Comment by amurashinffdc** [comment]
Are there any updates on this issue?

**Comment by bmblb** [comment]
I'm afraid not. We've applied some fixes (e.g. column/row reorder) but we are not working on LWS support at the moment. We hope to start on it Q3 this year. Do you need this support sooner? Are there any specific blockers we can help with?

**Comment by amurashinffdc** [comment]
No immediate blockers, just wanted to check on the progress to help assess our own priorities.

Thanks

**Comment by amurashinffdc** [comment]
Hello, it has been a while since we had an update on this issue. Recently, Salesforce has published Winter'23 release notes where it continues its commitment to LWS by enabling it by default in all new orgs.

https://help.salesforce.com/s/articleView?id=release-notes.rn_lwsec_new_orgs.htm&type=5&release=240

The two issues mentioned above are thus becoming more pressing. The overrides I proposed appear to be working for us thus far but I'm not sure how reliable/future proof is this approach. We would like to get your point of view on this.

**Comment by bmblb** [comment]
Applied patches, everything seems to work fine.

Found a problem unrelated to the patch: https://github.com/bryntum/support/issues/5172
