### ISSUE TITLE
Should be possible to opt out of header when using collapsible

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3749]
To handle it programmatically

**Comment by dongryphon** [comment]
Should this be independently configurable for expanded and collapsed state?

**Comment by dongryphon** [comment]
The reason the header was being forced to appear is the `tool` config for the collapse/expand tool. With that disabled, the header may or may not appear (based on other configs). My PR fixes the issues that ensue with `inline` collapse mode (the only public mode since `overlay` is private atm) and adds tests that exercise things via the API.
