### ISSUE TITLE
Project start is not recalculated when all tasks are moved further

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3799]
Reproducible on advanced demo. If you move all tasks further when no task matches project start date, project start is not updated.

Question is: should we update project dates in such cases?

**Comment by arcady-zherdev** [comment]
This is by design: a _forward scheduled_ project _start date_ is fixed and its _end date_ is calculated.
For a _backward scheduled_ project it's vice versa: _end date_ is fixed and _start date_ is calculated.
Otherwise it's an infinite cycle: tasks depend on project start date ..project start date depends on tasks...
