### ISSUE TITLE
Field picker is not aligned on scroll

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3941]
Reproducible on gantt webcomponents demo: start editing start date field, open picker and then scroll component vertically - picker gets misaligned to the the field.

It appears to be a regression caused by #3709 - `doHideOrRealign` moved to the animation frame callback and event's target gets nullified. It should be stored in the event, probably in a different property.

![image](https://user-images.githubusercontent.com/45400762/147251417-0eb7de8c-daeb-4e62-9bac-fad5e3a55924.png)

**Comment by ExtAnimal** [comment]
The fix for this appears to be this extra cloning in `EventHelper.fixEvent`. It seems that when it gets to the final handler (`doHideOrRealign`) the `target` is null. Cloning events from inside the shadowRoot like this appears to prevent this.

![Screenshot 2022-03-01 at 14 44 45](https://user-images.githubusercontent.com/200516/156180148-38161b9c-fcba-4d5e-a96d-89d8f2d89f07.png)
