### ISSUE TITLE
Error thrown when event is updated in a non-painted scheduler

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4212]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=20306&p=100805#p100805)
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'height')
    at HorizontalRendering.onRenderDone (HorizontalRendering.js:1755:93)
    at RowManager.trigger (Events.js:1288:35)
    at RowManager.renderRows (RowManager.js:1008:14)
    at HorizontalRendering.js:1071:38
    at Scheduler.runWithTransition (TimelineBase.js:1709:9)
    at HorizontalRendering.refreshResources (HorizontalRendering.js:1066:23)
    at HorizontalRendering.onProjectRefresh (HorizontalRendering.js:437:20)
    at ProjectModel.trigger (Events.js:1288:35)
    at ProjectModel.doCommitAsync (SchedulerCoreProjectMixin.js:469:20)
```

https://www.bryntum.com/examples/calendar/calendar-scheduler/

When I try to create an event when I include the Timeline view, but not defining it as the default view, the event isn't created and leaves this error :
Uncaught (in promise) TypeError: t._bodyRectangle is undefined

To reproduce the bug:
Go to the scheduler timeline example (link)
Change 'mode' value from 'timeline' to another value (week for example)
Try to create a new event

**Comment by ExtAnimal** [comment]
The issue is that Schedulers/Gantts don't deal with being `display:none`. They have never been rendered as cards in a card layout. Their data change listeners always refresh the UI.

In their scheduling of a refresh, they have to do as the Calendar modes do.

If not currently visible, then add a `once : true` listener for the next `paint` event (unless it's is already added) to do a refresh the next  time we get painted (different to show - could mean that an owner container gets shown).

`CalendarMixin` has this:

```
    refresh() {
        const me = this;

        // If we're being called programmatically, cancel upcoming delayed refreshes.
        me.refreshSoon.cancel();

        // Only refresh immediately if we are visible.
        if (me.isVisible) {
            me.refreshNow();
        }
        // Otherwise wait till next time we get painted (shown, or a hidden ancestor shown)
        else if (me.findListener('paint', 'refreshNow', me) === -1) {
            me.on({
                paint   : 'refreshNow',
                thisObj : me,
                once    : true
            });
        }
    }
```
