### ISSUE TITLE
Tasks disappear when clicking Change data in demo

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4337]
To reproduce this:
1. go to [inline-data](https://bryntum.com/examples/gantt/frameworks/react/javascript/inline-data/build/) example
2. click on the `CHANGE DATA` button.
![change-data-problem](https://user-images.githubusercontent.com/75997756/157427305-e7cfe336-bf6d-4a7f-8bfe-3b1e4538b452.gif)

**Comment by ExtAnimal** [comment]
Thos could be an ordering issue. Stores have to be loaded in correct order, and this is now handled automatically if `setConfig` is used.

So instead of

```
            setTasks(initialData.tasks);
            setAssignments(initialData.assignments);
            setDependencies(initialData.dependencies);
            setResources(initialData.resources);
            setTimeRanges(initialData.timeRanges);
            setCalendars(initialData.calendars);
```

try

```
this.setConfig({
    tasks : initData.tasks,
    dependencies : initData.dependencies
   ...etc...
});
```

`setConfig` sets up the config system's initGetters which pull in configs in the correct order.

And a related issue is https://github.com/bryntum/support/issues/4312

Multiple property changes being injected from a framework should be gathered up, and on the next AF, fed through into our world via `setConfig` so that ordering is handled

**Comment by matsbryntse** [comment]
Same as https://github.com/bryntum/support/issues/4370 ?

**Comment by jsakalos** [comment]
Unfortunately, it’s not fixed. Better to say, we now have another issue. To reproduce (in the `inline-data folder`):
```
grunt npm:build
grunt fw:local:switch:offline
npm i && npm start
```
Now click “Change Data” button (works). Click “Change Data” button again and it crashes with:
```
gantt.module.js:48231 Uncaught Error: Parent node with id 1 not found, cannot add children.
    at gantt.module.js:48231:1
    at Map.forEach (<anonymous>)
    at Object.add (gantt.module.js:48227:1)
    at Object.add (gantt.module.js:53319:1)
    at Object.syncDataset (gantt.module.js:52995:1)
    at Object.setStoreData (gantt.module.js:54861:1)
    at Object.setStoreData (gantt.module.js:128347:1)
    at Object.setStoreData (gantt.module.js:193851:1)
    at Object.set data (gantt.module.js:54795:1)
    at Object.set data (gantt.module.js:195577:1)
```
I’ve never seen this error message before so I suspect it was introduced by the fix.
