### ISSUE TITLE
Scroll changes when clicking Edit button with Project row selected

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#467]
advanced demo

**Comment by ExtAnimal** [comment]
It's https://github.com/bryntum/bryntum-suite/blob/master/SchedulerPro/lib/SchedulerPro/feature/ProTaskEdit.js#L225

It scrolls the taskbar into view.

The options currently available to request *how* to scroll are

* start - meaning the start of the requested element is aligned to the start of the viewport (eg how configs are done in the docs app)
* end - the requested element's end is aligned to the end of the viewport.
* center - the center of the requested element is centered in the viewport
* nearest - Scroll by the least amount of scrolling to bring the element fully into view. *fully*. *If possible*

Now the default is "nearest" to do the minimum. But if the element exceeds the viewport dimensions, what should it do? It scrolls by the minimum to get as much of the element into view as possible.

Which is what you see it doing.

The question is *how* to ask for something to be scrolled into view. How to tell it exactly what you have in your mind as the optimum action for every circumstance.

Some kind of extra option for "nearest" about how many pixels is the minimum you need to see in the view?

Because if there's only 1 pixel showing, you are going to want *some* scrolling to show it in some form.

**Comment by matsbryntse** [comment]
Not reproducible in 4.0
