### ISSUE TITLE
Multi components ("thin") NPM bundles

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4670]
Should be possible to use any components together on 1 page using npm packages import.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21259&p=105728)
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24898&p=123739)
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=24862&p=123533)
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25013&p=124372#p124372)
[Forum post](https://forum.bryntum.com/viewtopic.php?p=125996#p125996)
[Forum post](https://forum.bryntum.com/viewtopic.php?p=126053#p126053)
[Forum post](https://forum.bryntum.com/viewtopic.php?p=127050#p127050)

**Comment by projul** [comment]
Is there a anticipated release date for this feature?

**Comment by SergeyMaltsev** [comment]
Currently we have no ETA for this feature request. 
It could be a part of  5.x or 6.x release.

Please contact us at [Professional Services](https://www.bryntum.com/services) if you want sponsor and speedup this development.

**Comment by chuckn0rris** [comment]
Another request here https://forum.bryntum.com/viewtopic.php?f=51&t=25013&p=124372#p124372

**Comment by zerowww** [comment]
@chuckn0rris Hello, does it mean we can't have both Calendar and Scheduler live in the same application at the moment ?????
I'm trying to upgrade to angular 15 from angular 14 and to bryntum scheduler/calendar 5.3.6 (latest release) from bryntum scheduler/calendar 5.1.1 and I have this exact same error that I can't solve by myself ..

**Comment by datiecher** [comment]
Is the ETA on this issue still next month? We're evaluating the purchase of your entire suite of products, but being unable to use more than one component in the same application is a deal-breaker for us.

**Comment by SergeyMaltsev** [comment]
@datiecher it is currently under development. It works but not ready for public yet.
We hope to publish alpha within a coming month.
If you have a license then you will be able to test it sooner at pre-alpha period through Customer Zone download.

**Comment by tcs-rliess** [comment]
@SergeyMaltsev any news regarding the alpha version? We need this urgently, too.

**Comment by jimmylarkin** [comment]
@SergeyMaltsev, which build can we download from the Customer Zone to test it?

**Comment by zerowww** [comment]
@SergeyMaltsev It looks like it will be available on 5.6.0 release ?
Do you confirm ? How long will it take to get there approximately please ?

**Comment by SergeyMaltsev** [comment]
@zerowww this won't delay release of thin npm bundles by time. Just we need urgent `5.5.0` release.
Thin packages will be as part of 5.6.0.
We plan 5.6.0 alpha release in coming week or two.

**Comment by ashupp** [comment]
Stumbled upon this issue after upgrading to 5.5.0
So the problem is just the fact we are using scheduler and grid in one application?
Is there any current workaroud?

**Comment by SergeyMaltsev** [comment]
@ashupp 
To use Scheduler and Grid use `@bryntum/scheduler` package which has both products inside. 
No need for thin implementation for Grid + Scheduler.

**Comment by ashupp** [comment]
> @ashupp To use Scheduler and Grid use `@bryntum/scheduler` package which has both products inside. No need for thin implementation for Grid + Scheduler. Please note that products are licensed separately even if you may use one installed package for both.

Thank you - Interesting. I will try this. Yes, we have both licenses. Scheduler Pro and Grid.

**Comment by SergeyMaltsev** [comment]
I have this development screen capture to share with you. 
These are test applications for Angular, React + Vite, and Vue 3 + Vite. 
They use "thin" bundles that can be combined for any products required in your application. 
These demos show all of Bryntum products running within one application.
Thin bundles also support invisible `ProjectModel` components, which can be shared across products to display and interact with the same data.

An alpha release will be available pretty soon, allowing you to experience the features of thin bundles.

![thin-apps](https://github.com/bryntum/support/assets/57486330/0963874a-30c7-4d6b-94e6-656a3644ed41)

**Comment by SergeyMaltsev** [comment]
@datiecher we are working to release alpha next week (may be week after). 
We need some time for preparing integration guides and running tests to be sure everything is ok even for alpha.
Hope this will be the date.

**Comment by SergeyMaltsev** [comment]
We are happy to introduce new Bryntum 5.6.0 alpha 1 release with a new set of npm packages and framework components,
that allows combining multiple Bryntum products in the same application.

Thin library packages:

| Package                    | Purpose                                     |
|----------------------------|---------------------------------------------|
| @bryntum/core-thin         | Bryntum Core data and UI components package |
| @bryntum/grid-thin         | Bryntum Grid component package              |
| @bryntum/scheduler-thin    | Bryntum Scheduler component package         |
| @bryntum/schedulerpro-thin | Bryntum Scheduler Pro component package     |
| @bryntum/gantt-thin        | Bryntum Gantt component package             |
| @bryntum/calendar-thin     | Bryntum Calendar component package          |
| @bryntum/taskboard-thin    | Bryntum TaskBoard component package         |
| @bryntum/engine-thin       | Bryntum Scheduling engine component package |

Thin Angular wrapper packages:

| Package                            | Purpose                                          |
|------------------------------------|--------------------------------------------------|
| @bryntum/core-angular-thin         | Bryntum Core UI widgets Angular wrappers package |
| @bryntum/grid-angular-thin         | Bryntum Grid Angular wrapper package             |
| @bryntum/scheduler-angular-thin    | Bryntum Scheduler Angular wrapper package        |
| @bryntum/schedulerpro-angular-thin | Bryntum Scheduler Pro Angular wrapper package    |
| @bryntum/gantt-angular-thin        | Bryntum Gantt Angular wrapper package            |
| @bryntum/calendar-angular-thin     | Bryntum Calendar Angular wrapper package         |
| @bryntum/taskboard-angular-thin    | Bryntum TaskBoard Angular wrapper package        |

Thin React wrapper packages:

| Package                          | Purpose                                        |
|----------------------------------|------------------------------------------------|
| @bryntum/core-react-thin         | Bryntum Core UI widgets React wrappers package |
| @bryntum/grid-react-thin         | Bryntum Grid React wrapper package             |
| @bryntum/scheduler-react-thin    | Bryntum Scheduler React wrapper package        |
| @bryntum/schedulerpro-react-thin | Bryntum Scheduler Pro React wrapper package    |
| @bryntum/gantt-react-thin        | Bryntum Gantt React wrapper package            |
| @bryntum/calendar-react-thin     | Bryntum Calendar React wrapper package         |
| @bryntum/taskboard-react-thin    | Bryntum TaskBoard React wrapper package        |

Thin Vue 3 wrapper packages:

| Package                          | Purpose                                        |
|----------------------------------|------------------------------------------------|
| @bryntum/core-vue-3-thin         | Bryntum Core UI widgets Vue 3 wrappers package |
| @bryntum/grid-vue-3-thin         | Bryntum Grid Vue 3 wrapper package             |
| @bryntum/scheduler-vue-3-thin    | Bryntum Scheduler Vue 3 wrapper package        |
| @bryntum/schedulerpro-vue-3-thin | Bryntum Scheduler Pro Vue 3 wrapper package    |
| @bryntum/gantt-vue-3-thin        | Bryntum Gantt Vue 3 wrapper package            |
| @bryntum/calendar-vue-3-thin     | Bryntum Calendar Vue 3 wrapper package         |
| @bryntum/taskboard-vue-3-thin    | Bryntum TaskBoard Vue 3 wrapper package        |


Please refer to new integration guides for using new thin packages.
The attached basic demos show how to integrate multiple products within one application.

**Please note that you need a license for each product in order to gain npm access for the product's thin packages.**

| Framework | Multiple Products Integration Guide                                                           | Demo                                                                               |
|-----------|---------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|
| Angular   | [Angular guide](https://bryntum.com/products/grid-next/docs/guide/Grid/integration/angular/multiple-products) | [angular.zip](https://github.com/bryntum/support/files/12405338/angular.zip)       |
| React     | [React guide](https://bryntum.com/products/grid-next/docs/guide/Grid/integration/react/multiple-products)     | [react-vite.zip](https://github.com/bryntum/support/files/12405339/react-vite.zip) |
| Vue 3     | [Vue guide](https://bryntum.com/products/grid-next/docs/guide/Grid/integration/vue/multiple-products)         | [vue-3-vite.zip](https://github.com/bryntum/support/files/12405342/vue-3-vite.zip) |

**Comment by johnny090807** [comment]
When i install the "5.6.0-alpha-1" This issue is still not fixed for react. Is there another version i would need for it to work? The documentation [React guide](https://bryntum.com/products/grid-next/docs/guide/Grid/integration/react/multiple-products) you provided above, goes to grid documentation "5.6.0-beta-2". Can you please help me?

**Comment by SergeyMaltsev** [comment]
Please use latest stable `5.6.0` version.
Please open a question on [support forum](https://forum.bryntum.com/) with details on the problem and attach your code which we can run and build.

**Comment by SergeyMaltsev** [comment]
React guide for thin bundles is the same for all products.

**Comment by cngoEnsite** [comment]
I can't use gantt and taskboard on the same project. (version 5.6.7) What should I do next?

**Comment by SergeyMaltsev** [comment]
@cngoEnsite 
You can check attached sample apps above in this thread.
If you still have an issue please create a question at [support forum](https://forum.bryntum.com/) here with attached project to check.

**Comment by isaelsilva1039** [comment]
Olá, boa tarde. Tenho uma aplicação onde utilizo dois recursos, o BryntumGantt e o BryntumCalendar. No entanto, esses dois recursos estão entrando em conflito.

Aplicação 
![image](https://github.com/bryntum/support/assets/71187451/83247613-699d-48fa-bdf3-271454c0897a)


erro 
![image](https://github.com/bryntum/support/assets/71187451/fde76d6c-89c0-424f-8ae8-50519d821c1e)

**Comment by chuckn0rris** [comment]
Hello [isaelsilva1039](https://github.com/isaelsilva1039),

Unfortunately we do not speak this language. Please use english and create a topic in our Support Forum for assistance.
https://forum.bryntum.com/

Thank you!

**Comment by SergeyMaltsev** [comment]
@isaelsilva1039 

You have used full packages instead of thin ones.
That leads to the error described in the guide for using multiple products here.
https://bryntum.com/products/gantt/docs/guide/Gantt/integration/react/multiple-products

Please follow it to use thin packages.

You may find application samples attached above in this github thread.
