### ISSUE TITLE
EventStore not being updated when removing event from list view

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4774]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=21469&p=106229#p106229)

There is a bug when we remove some events from the list view using the Calendar.

Check the video with an example

https://user-images.githubusercontent.com/16693227/172435300-3c0f4106-ac10-4057-b492-94ab2cf5dba9.mp4

The expected behavior is that when we delete something inside the event list, the event store should be updated properly and trigger all the related events.

**Comment by ExtAnimal** [comment]
There are a couple of issues here.

The Grid's store is a **separate copy** of the Calendar's event store because it is sorted into date order and then filtered to show only the selected date range. But is also subject to possibly other features on the grid like grouping and additional filtering (Using the grid feature), and it should not affect the overall Calendar store. This is in the `EventList` Calendar widget class.

The events are ordered, and the required date range is done using a Filter:

![Screenshot 2022-06-09 at 07 04 18](https://user-images.githubusercontent.com/200516/172768409-bf641866-e745-43c3-a7ac-c1cfb3732e92.png)

In the `release` branch, the Grid's context menu feature is allowed to run, and that deletes from the Grid's Store which the Calendar's store knows nothing about, so they see this bug.

In the `master` branch, the *Calendar's* context menu feature runs, removing the event is done from the Calendar's store and this works.

But in principle, mutations to the Grid's store should be mirrored in the Calendar's store. I can't remember why the `EventList`'s store is not a *chained* store off the Calendar's eventStore. It's now just a copy created from the same configuration. If it is a chained store, it can use the `doRelayToMaster` config which relays mutations to the master store.

**Comment by isglass** [comment]
Fixed by an earlier change to the context menu for the event list
