### ISSUE TITLE
Cell tooltip remains when hovering over blank cells

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4915]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21720&p=107380#p107380)

This is reproducible in the "Cell tooltip demo". 

Hover over a cell with a tooltip (for example, the City column "Paris" cell)
Move mouse to an empty cell (for example, the City column first row)
The previous tooltip shows on the empty cell (see screenshot)

Thanks.
![Screenshot 2022-07-11 at 09.07.19.png](https://www.bryntum.com/forum/download/file.php?id=18000)

**Comment by ExtAnimal** [comment]
It's because of the attempt to bypass the config system's rejection of "non  changes". It actually defeats the object:

```
        if (me.getHtml) {
            // Ensure the html setter does not veto the operation as a no-op.
            // Because of beforeShow listeners augmenting the content.
            me._html = null;
```

So when `null` is returned from the renderer, that's a no-change  to the `_html` property, so the updater doesn't run.

We need to set the old value to something unlikely. eg:

```
me._html = NaN;
```

Nothing equals `NaN`. Not even `NaN`!
