### ISSUE TITLE
Button pressed/hover state sticks after click

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#492]
https://www.bryntum.com/examples/gantt/advanced/

click zoomOut button

<img width="294" alt="Screenshot 2020-03-30 at 14 38 12" src="https://user-images.githubusercontent.com/218570/77913181-18802900-7294-11ea-83f2-2c996e99904b.png">

Should feel like clicking button https://material.io/components/buttons/

**Comment by pmiklashevich** [comment]
Caused by this line in Popup.onDocumentMouseDown
```
        // Focus moves unrelated to where the user's attention is upon this gesture.
        // Go into the keyboard mode where the focused widget gets a rendition so that
        // it is obvious where focus now is.
        // Must jump over EventHelper's global mousedown listener which will remove this class.
        me.setTimeout(() => document.body.classList.add('b-using-keyboard'), 0);
```

**Comment by ExtAnimal** [comment]
It's not that. That will cause focus to be shown. But the next usage of the mouse should clear it.

Because of ```EH.on({
    element : document,
    mousedown() {
        if (!DomHelper.isTouchEvent) {
            DomHelper.usingKeyboard = false;
            document.body.classList.remove('b-using-keyboard');
        }
    },
```

But the Popup's `onDocumentMouseDown` listener is not being removed upon hide, or somehow keeps being invoked by subsequent mousedowns, resulting in the class being added back.

This scheme worked, and has been recently regressed.

**Comment by ExtAnimal** [comment]
It's because of animatedShow I think

The Popup's mousedown listener is added onShow which happens before the animation finishes.

This is logical and desired, because the Popup is in the DOM and active and layed out and ready for business, and apps should not have to pause for the "eternity" of an animation to proceed with business like loading data and such.

Calling code can wait for it to be *completely* finished by using the `Promise` returned from show. But we need a way to *internally* hook to after any animation has finished.

I can take this one when I get fully back.

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/993
