### ISSUE TITLE
Checkbox column bug when clicked, not checked on first click

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5052]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=22016&p=108854#p108854)

In the basic Scheduler demo, add a check column like this (listeners add just for debugging purposes):

```
columns          : [
        {
            type      : 'check',
            width     : 55,
            listeners : {
                toggle(check) {
                    console.log('check', check);
                }
            }
        },
        { text : 'Name', field : 'name', width : 130 }
    ]
```
You will see that we need to click twice in the checkbox to mark it. Even with the listeners displaying the right value in the first click (check the screenshot attached).

![Screen Shot 2022-08-10 at 3 30 39 PM](https://user-images.githubusercontent.com/16693227/183990313-bf00ebd4-1dab-4f12-9456-fb54d0335471.png)

**Comment by ExtAnimal** [comment]
It works fine if there's a `field` to which the column maps which *holds* the checked/unchecked value.

What is happening is that the renderer is re-rendering that cell on change. It sets the checkbox's value to `undefined` because there's no `field` to get a value from. And `undefined` is casted to `false`, so it unchecks.
