### ISSUE TITLE
Vertical scroll flickers and lags

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#539]
https://bryntum.com/forum/viewtopic.php?f=44&t=13738

1. View jumps up and down when scrolling
Start the attached example.
Scroll to the bottom.
Press the scroll wheel and scroll upwards at a slow constant speed.
Also can scroll up with mouse wheel slowly to notice it.

2. Scrolling speed is not consistent / vertical scroll lags
Start the attached example.
Scroll to the bottom.
Scroll to the top with the mouse wheel. The bottom 50 resources from the bottom can be scrolled past quickly. The top 50 resources are much slower to scroll past.

Scroll problem is present in all browsers, but it's most noticeable in Firefox.

[bryntum_scheduler_issue.zip](https://github.com/bryntum/support/files/4469953/bryntum_scheduler_issue.zip)

Similar issue (https://app.assembla.com/spaces/bryntum/tickets/8953-bigdataset-scroll-performance/details)
Also reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=11762
Steps to reproduce on the demo (only reproducible with real mouse wheel) https://www.bryntum.com/examples/scheduler/bigdataset/:
1. scroll down fast using mouse wheel
2. scroll up fast using mouse wheel returning wheel to initial position
you will notice glitches when scrolling up and putting wheel to initial position won't return view to same position.

Not reproducible with touchpad
scroll performance.webm

**Comment by ExtAnimal** [comment]
It's not flickering and it's not lagging.

Drag your eyes away from the scrollbar on the right.

As you scroll, focus solely on the resource names on the left. Scroll carefully, and you will see it working correctly.

If you stare at the scrollbar, you will see the effect of the recalculation of the scroll range. As rows of different heights are encountered, the estimate of how tall the dataset is has to change. Otherwise you might not be able to scroll to the end

The scrollbar will wobble in size and position. This is expected the way the grid (and all variable row height grids) work.

If it renders a run of 200px tall rows, it will increase the dataset height. That will cause the scrollbar to jump upwards and become smaller.

If it then encounters a run of rows which are only 35px tall, than it has to recalculate again to make the scroll range smaller. Otherwise there might be blank space to scroll into after the data has finished. This will make the scrollbar grow and jump downwards.

This effect has always been visible in variable row height examples where the row heights vary by more than a few pixels on *average*. The ExtScheduler examples and the Vanilla scheduler examples do not vary enough to make this noticeable much. It is noticeable only if you look very carefully.

We could fix the dataset height in `Scheduler` by calculating it from the layouts of _every event in the dataset_.

For example, Scheduler could have

```
calculateScrollRange() {
    let result = 0;
    scheduler.resourceStore.forEach(r => {
        // Events for this resource
        const evts = scheduler.eventStore.getEventsForResource(r);

        for (e of evts) {
            const b = scheduler.getResourceEventBox(e, r);

            // The bottom of the event box
            result = Math.max(result, b.bottom);
        }
    });
    return result;
}
```

Now this might be expensive with lots of resources and events. And obviously it would have to be run on every data change because any change could cause the layout to change (eg, moved to another resource, or time change causes the event to overlap, or cease to overlap another)

**Comment by ExtAnimal** [comment]
In fact the above solution will not work. Because it uses the calculated `averageRowHeight` which is what varies during scroll.

But some similar solution will have to be wrought.

The event layout algorithm within `HorizontalMapper.layoutEvents(scheduler, resource, row)`  will have to be made available as a pure layout calculator for use by this dataset height calculation part.

**Comment by ExtAnimal** [comment]
`HorizontalMapper` needs this immediately below `layoutEvents`

```
    /**
     * Calculates the necessary row height for the passed resource
     * @private
     * @param {Scheduler.view.Scheduler} scheduler
     * @param {Scheduler.model.ResourceModel} resource
     * @returns {Number} The required row height in pixels.
     */
    calculateRowHeight(scheduler, resource) {
        const
            me             = this,
            { timeAxis }   = me,
            { eventStore } = scheduler,
            resourceId     = resource.id,
            resourceEvents = eventStore.getEventsForResource(resourceId),
            // When using an AssignmentStore we will get all events for the resource even if the EventStore is filtered,
            // handle this be excluding "invisible" events here
            availableEvents = eventStore.isFiltered ? resourceEvents.filter(eventRecord =>
                eventStore.indexOf(eventRecord) > -1
            ) : resourceEvents,
            // Call a chainable template function on scheduler to allow features to add additional "events" to render
            // Currently used by ResourceZones
            allEvents     = scheduler.getEventsToRender(resource, availableEvents) || [],
            events        = allEvents.filter(e => timeAxis.isTimeSpanInAxis(e)),
            // Generate layout data for events belonging to current row which are within the TimeAxis
            eventsTplData = events.reduce((result, event) => {
                const eventBox = scheduler.generateTplData(event, resource);

                // Collect layouts of visible events
                if (eventBox) {
                    result.push(eventBox);
                }

                return result;
            }, []);

        // If there are no events within the rendering zone, use default row height.
        if (!eventsTplData.length) {
            return scheduler.rowHeight;
        }

        // Ensure the events are rendered in natural order so that navigation works.
        eventsTplData.sort(scheduler.horizontalEventSorterFn || me.eventSorter);

        const
            layout = scheduler.currentEventLayout,
            // Only events and tasks should be considered during layout (not resource time ranges if any)
            layoutEventData = eventsTplData.filter(d => d.event.isEvent || d.event.isTask);

        // Event data is now gathered, calculate layout properties for each event
        if (scheduler.eventLayout === 'stack') {
            const
                nbrOfBandsRequired = layout.applyLayout(layoutEventData, resource),
                heightPerEvent     = scheduler.rowHeight - scheduler.resourceMargin * 2;

            return (nbrOfBandsRequired * heightPerEvent) + ((nbrOfBandsRequired - 1) * scheduler.barMargin) + scheduler.resourceMargin * 2;
        }
        return scheduler.rowHeight;
    }
```

Then `Scheduler` needs

```
calculateScrollRange() {
    let result = 0;
    scheduler.resourceStore.forEach(r => {
        result += scheduler.currentOrientation.calculateRowHeight(scheduler, r);
    });
    return result;
}
```

Then a slim `RowManager` subclass could be implemented for Scheduler which keeps the scroll range correct. This should be opt-in behaviour.

**Comment by ExtAnimal** [comment]
Branch started: https://github.com/bryntum/bryntum-suite/pull/1037

@pmiklashevich you can take it from here
