### ISSUE TITLE
Combo not sized the same when editable vs non-editable

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#5674]
Live demo looks bad
Docs for `#Core/widget/Combo`

![image](https://user-images.githubusercontent.com/57486330/204251304-3d02b59e-398a-48bd-8962-a5a1ae18a3a4.png)

**Comment by ExtAnimal** [comment]
In the Material theme, the outer element should be `flex-direction : column` so that the `<label>` naturally lays out above the field inner container. The CSS for it can then be much simplified.

Then the `label` element just needs so be `transformed` to translate it. It does not need `position:absolute` which takes it out of the layout. It should stay in the layout contributing to the natural height of the widget. 

So in Material, the `label` only needs

```
    transition    : all 0.2s;
    white-space   : nowrap;
    overflow      : hidden;
    text-overflow : ellipsis;
    margin-bottom : 0.1em; // Add a little more space between the label and the field
```

So when *not focused*, the `label` needs

```
    transform: translate(0, 3em);
```

To push it down over the input area to make it look like a placeholder.
