### ISSUE TITLE
EventStore `loadDateRange` event fired excessively

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5828]
http://lh/bryntum-suite/scheduler/examples/infinite-scroll/
Note behavior on page load

Needs a review

**Comment by ExtAnimal** [comment]
The event is just an informational event from the `EventStore` saying it has been asked for a date range of events _*for some resource*_. The key here is "For some resource".

Its API docs have always sad `Fired when a range of events is requested from the {@link #function-getEvents} method.`

The event is fired more than once only in Scheduler because Scheduler loops through the rendered resources and for each rendered resource calls

```
getEvents({
    startdate : ...,
    endDate : ...,
    resourceRecord : resource
});
```

so you will get one call for each rendered row. The `resourceRecord` is different each time.

*_The resulting actual event load will be different each time_*. If users are actually using this event for something, each event has a real, different meaning because the resource is different.

We should really add the `resourceRecord` to the event.
