### ISSUE TITLE
[Vue 2] [Calendar] Calendar events `+x more` in the month view setting.

### ISSUE THREAD

**Issue by dcruz1990** [bryntum/support#5890]
I have this situation:
![image](https://user-images.githubusercontent.com/43586145/211040037-74b4dd7f-67c1-44b2-8a2a-e1822b287aae.png)
Why calendar is rendering this white space instead of just rendering the elements normally?

**Comment by ExtAnimal** [comment]
I cannot see how your events flow in that screenshot.

But I assume these are long running events which flow there from deep down in previous cells, in which case the events remain in their row. If events jumped upwards wherever space was available they would become disjointed and appear as continuations of events in neighbouring cells.

All calendars which render fixed height day cells behave in this way with long running events at deep row levels which flow forwards into future cells.

Google Calendar with events flowing into December 1 at deep row level:

<img width="1653" alt="Screenshot 2023-01-07 at 12 45 44" src="https://user-images.githubusercontent.com/200516/211149033-89235fbb-0144-4d7c-ad67-ca3e3d29e2db.png">


The same data displayed by Apple Calendar:

<img width="1255" alt="Screenshot 2023-01-07 at 12 39 02" src="https://user-images.githubusercontent.com/200516/211149056-52243898-93f9-4bd3-857f-de7443d38e7b.png">

After I expand the screen to make the cells big, you can see those deep event rows at the bottom of the taller December 1 cell:

<img width="963" alt="Screenshot 2023-01-07 at 12 49 46" src="https://user-images.githubusercontent.com/200516/211149214-3fcee5f1-3673-4208-8e8e-73f60304a321.png">

**Comment by ExtAnimal** [comment]
Week rows in a `MonthView` can be individually, or en masse, set to auto height so that they expand to show all events when there are many, or recede back to a minimum height when few.

See this example: https://bryntum.com/products/calendar/examples/bigdataset/

### Individual row auto height:

<img width="519" alt="Screenshot 2023-01-07 at 12 57 16" src="https://user-images.githubusercontent.com/200516/211149466-8a862b58-8a19-4b4c-b68c-57bc35f9f186.png">

### En masse row auto height:

<img width="318" alt="Screenshot 2023-01-07 at 12 58 00" src="https://user-images.githubusercontent.com/200516/211149502-84662a4c-783f-4f21-8aaa-67b0f7765970.png">
