### ISSUE TITLE
Document new TreeStore not firing 'remove' event for node move

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6009]
https://github.com/bryntum/support/issues/5371

changelog & upgrade guide

**Comment by FlowIT-JIT** [comment]
@matsbryntse You are recommending developers to use this flag, but not providing any documentation or TypeScript definition support at the same time?

Change log:
`As of version 6.0, remove event will no longer be fired when moving a node in a tree store. To enable this behavior now (recommended), you can set a new fireRemoveEventForMoveAction on your tree store to false (#5371)`

Could you please provide an example of how to set this? We don't use the ProjectModel but apply data directly to the gantt instance:

```
<BryntumGantt
    startDate={props.data.startDate}
    endDate={props.data.endDate}
    tasks={props.data.tasks}
    dependencies={props.data.dependencies}
    columns={props.data.columns}
    criticalPathsFeature={{ disabled: !props.showCriticalPath }}
    {...props.config}
/>
```

My current approach is this (which I have to hack with an _any_ cast due to lack of TypeScript support).
Would this be a viable solution? It seems to work - but will it also work going forward?

```
<BryntumGantt
    ref={(gantt: BryntumGantt) => {
        (gantt.instance as any).fireRemoveEventForMoveAction = false; // eslint-disable-line @typescript-eslint/no-explicit-any
    }}
    .... etc.
/>
```

-- Thanks

Attention @mhbuur

**Comment by matsbryntse** [comment]
Fair enough, we'll document this flag for the next patch. Thanks for the feedback!

**Comment by FlowIT-JIT** [comment]
@matsbryntse Thanks. Is my current solution viable?

**Comment by matsbryntse** [comment]
It should be set as a config param on the taskStore, not on the Gantt.

**Comment by FlowIT-JIT** [comment]
With the release of 5.2.10 fireRemoveEventForMoveAction has now been declared on various types - but not on the TaskStore config property.

![image](https://user-images.githubusercontent.com/10479064/220262335-7f8d0003-1628-4a2d-93ca-80d084ac19a8.png)

**Comment by jsakalos** [comment]
I have tried it in our Gantt inline-data example, version `5.2.10` and it seems to work on `Project Model` but does NOT work on `taskStore` on Gantt. The typing needs to be added on taskStore too.
<img width="690" alt="Screenshot 2023-02-21 at 13 39 27" src="https://user-images.githubusercontent.com/204844/220348098-d9a4ab28-edab-488a-9660-1d2bc8dc8398.png">

**Comment by SergeyMaltsev** [comment]
Moved to separate issue
https://github.com/bryntum/support/issues/6236
