### ISSUE TITLE
Start date field doesn't allow to move a manually scheduled task before the project start date

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6256]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23996&p=118789#p118789)

Please check the video on how to reproduce it

https://user-images.githubusercontent.com/75997756/221508369-bfafef6b-9ea2-41a3-b0d5-41fbe4a798ad.mp4

**Comment by arcady-zherdev** [comment]
The issue comes from changes we made in start date field:
```js
    get min() {
        return super.min || this.project?.startDate;
    }
```
We tried to prevents calendars freezing when they tried to fill internal cache for a huge time range.
But the solution breaks the ability of manual tasks to be scheduled before the project start. Need to find a proper way of solving both of the issues.

**Comment by arcady-zherdev** [comment]
Closing this since it duplicates older https://github.com/bryntum/support/issues/5585
