### ISSUE TITLE
Dependency adding/removing doesn't trigger sync

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6283]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=119134#p119134)

I have tried the 5.2.10 version and the issue is consistent.
Load Gantt & Add Dependency between 2 tasks. Set it as SS dependency
Remove dependency as shown in the attached recording
Sync API call will not trigger on save

To reproduce this
Need to enable `autoSync`
And put a sync url

Here is the video

https://user-images.githubusercontent.com/75997756/222407456-822c9399-d0e1-4002-bc14-5b7fb30fc59a.mp4

**Comment by snayyar-qb** [comment]
Is there any update on this issue, I can still reproduce it in version 5.4.0

**Comment by arcady-zherdev** [comment]
It's not a bug. If I understand the scenario correctly:
1. we add a dependency (we do not save changes to the server)
2. remove the dependency

And at this point we try to save changes to the server. But there aren't any.

After you added a record the store had changes (it had the new record to be saved to the server). The record was not sent to the server. And after you removed it the store has nothing to send to the server.

If you save the record after step #1 the removal would require sending changes to the server. Since in that case the record would be there and the server should've removed it too.
