### ISSUE TITLE
Incorrect Tooltip Icon when dnd inside a scrollable timeline

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6489]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=39&t=9649&p=120950#p120950)

Looks the tooltip icon will become incorrect inside a scrollable gantt when trying to drag and drop an event.
Not sure if it's bug, but we can reproduce this issue on [validation demo](https://bryntum.com/products/scheduler-for-extjs/examples/kitchensink/#examples/validation)
See attached a screen recording.
The Standard event are not allowed to drop to Resource Robot 3, but the tooltip icon in the screen recording at around 13s looks are allowed.

Thanks,
Jonathan

https://user-images.githubusercontent.com/7203098/228725760-66535f9a-3acd-4756-919b-d68efb920ae4.mov

https://user-images.githubusercontent.com/7203098/228725763-1df0e931-947b-48ea-99f5-45adef167f33.mov

**Comment by vincentcn** [comment]
Hi @chuckn0rris, any ETA of the fix? This issue has been raised for a long time.

**Comment by arcady-zherdev** [comment]
@vincentcn will check this next week and update you with ETA here

**Comment by arcady-zherdev** [comment]
@vincentcn Yes that's a bug. A bit of an edge case though.

When scroll happens the Scheduler tries to update the tooltip but it doesn't call `dndValidatorFn` function since it cannot provide all the input described in the function contract (namely it has no the last argument mouse DOM event).
I think that validation should be called anyway but this is covered with few tests so it's a breaking change.

We are not going to do a major release now. So to fix the issue I've added a new `callDndValidatorFnOnScroll` config on the Scheduler. Please set it to `true` to call validation as reaction on view scroll:
```js
var scheduler = Ext.create("Sch.panel.SchedulerGrid", {
    // call drag'n'drop validation on scroll events too
    callDndValidatorFnOnScroll : true
```

**Comment by vincentcn** [comment]
Thanks @arcady-zherdev.
To confirm it, `callDndValidatorFnOnScroll` has been supported in v6.1.22, right?

**Comment by arcady-zherdev** [comment]
@vincentcn yes it's added in v6.1.22
