### ISSUE TITLE
Toggling `EventResize` disabled state does not show resize handles

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6593]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=122113#p122113)

Hi!
We recently got around to bumping our Bryntum version from 5.1.3 to 5.2.10.
But I noticed that our resize functionality started giving issues.
To drag or resize events in our application we need to press and hold Ctrl.
This causes the resize feature to be enabled "disabled = false". (PlanScheduler, line 62)
First nothing really happened when doing this in the new version, until I tried adding "refreshWithTransition" after the feature toggle. That made it so that we can resize the events, but no resize handle is displayed.
To get the handle to display I need to move the cursor from the event to another or just out and back, this causes the handle to be displayed.

Steps to reproduce:
Hover over an event
Press and hold Ctrl
No handles to resize are visible but you can still resize if the cursor is moved to either side of the event.
Move the cursor to another event.
The handles to resize will become visible.

Hope this gives some indication of what can be the issue.

Thanks in advance!

**Comment by ExtAnimal** [comment]
Bug was introduced here: https://github.com/bryntum/bryntum-suite/pull/6079

The `b-sch-event-resizable-true` needs to be there if the feature is *present*, not if the feature is enabled.

Disabling the feature removes the overall controlling class `b-eventresize` from the whole scheduler which means that the handles will not show up because the CSS selects that.
