### ISSUE TITLE
Support readOnly field on model

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#665]
https://www.bryntum.com/forum/viewtopic.php?p=63534#p63534
https://www.bryntum.com/forum/viewtopic.php?p=79000#p79000
https://www.bryntum.com/forum/viewtopic.php?f=44&t=17156&p=85179#p85179
https://www.bryntum.com/forum/viewtopic.php?f=44&t=17720&p=87765#p87765
https://www.bryntum.com/forum/viewtopic.php?p=87986#p87986

**Comment by Qwertie-** [comment]
Is there any rough estimate for when we could see this implemented. Or any pointers we could use to implement this ourselves in the meantime?

**Comment by matsbryntse** [comment]
It affects a huge portion of our codebase as we have so many features that will need to respect this flag, so no quick fix I'm afraid.

**Comment by ExtAnimal** [comment]
It would be very easy to have the data setting method `inSet` consult a `readOnly` field and not perform the update if it is set.

To be decided is what happens if an update is requested on a readOnly record.

Probably just trigger an `attemptToModifyReadOnlyRecord` event in case any code is concerned.

If the app is not concerned, it will just silently leave the record unmodified.

**Comment by pmiklashevich** [comment]
For now to make one record read-only, need to prevent all features like cellEdit, drag, resize etc manually. Need to add a readOnly field to GridRowModel, convert GridRowModel into a mixin, mix up to ResourceModel and TaskModel (for now TaskModel does not extend GridRowModel). All feature should respect the readOnly value and prevent editing automatically.

**Comment by isglass** [comment]
The implementation in progress wont affect the datalayer, it will be checked by the UI to prevent editing etc.
