### ISSUE TITLE
Issues combining infiniteScroll with zoom

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6654]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24752&p=122880#p122880)

"We are currently setting up a quite full featured date navigation setup, with moving to dates, zoom in/out buttons, custom preset zoom levels among other things. We also want to use infiniteScroll, but when we enabled that we found that it doesn’t play nice with any of the mentioned features.

We’ve found examples you have of each feature, and I’ll try to describe how the error presents itself in each case. For each of the examples, just add infiniteScroll: true to the scheduler config.

1. Zooming, for example in [https://www.bryntum.com/products/schedulerpro/examples/resourceutilization/](https://www.bryntum.com/products/schedulerpro/examples/resourceutilization/). When having all of the event in the viewport, zooming in and out changes the range of dates visible to the future or past, often to the point where no events are visible anymore."

**Comment by marciogurka** [comment]
This behavior perhaps could be the zooming with scrolling that gets the pointer position to zoom in/out the scheduler, asking for more information to the user.

**Comment by ExtAnimal** [comment]
It's not "issues". It's not combining infinite scroll and zoom.

That works as well as the current scheme of cycling through ViewPresets can work.

The visual issues are all caused by the presence of the ResourceHistogram.

If you remove that, so that the example is just this:

![Screenshot 2023-06-06 at 17 09 36](https://github.com/bryntum/support/assets/200516/47da718c-cde8-4b7b-ad6c-787b94b9924c)

Then it all works fine.

The ResourceHistogram needs to be refactored. The TimeAxis is of course being changed on every zoom step right now because every zoom step is a ViewPreset change. And that causes a heavy recalculation in the ResourceHistogram widget with many async operations running into the future. And then more zooms arrive before that operation has finished and start it all off again.

And these two widgets are linked by being partnered so that any scroll in one, scrolls the other. I think @arcady-zherdev  is the expert on the ResourceHistogram widget. The cascade of operations from every zoom step needs to be tamed.

**Comment by arcady-zherdev** [comment]
@nige turned out to be not specific to the histogram... two scheduler instances give the same issue
