### ISSUE TITLE
`mergeCells` feature doesn't stick text in Scheduler

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6846]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25093&p=124769#p124769)

Hi Bryntum Team,

We are using Scheduler for our project and would like to use mergeCells option. As I can see in your demo for Grid https://bryntum.com/products/grid/examples/merge-cells/ In this demo if you scroll down the name of the megredCells stays sticky unless all rows for that city will be scrolled. 
So I would like to have  the same thing, but for Scheduler - resources part. 

I checked your example with merged Cells for Scheduler https://bryntum.com/products/scheduler/examples/merge-cells/ . In this example the mergeCells' name just scrolls out of the view. How can I make it stay sticky as in your Grid example. I have tried to change css but it seems like it's not helping. Are there any workaround on this ?

Thank you,
Maria

**Comment by ExtAnimal** [comment]
It's when there's a subgrid which offers scrolling in the X axis. It sets the subgrid to `overflow-x : auto`
Stickiness doesn't work with anything except overflow : visible. It's a terrible piece of design by W3C.

If the sub grid is configured with

```
subGridConfigs : {
    locked : {
        scrollable : {
            overflowX : 'visible',
            overflowY : 'visible'
        }
    }
}
```

Then the example "works".

But resizing a column wider causes the sub grid content to spill into the scheduler area. That gets fixed as the sub grid auto sizes after the mouseup.

But dragging the splitter to make the sub grid narrower completely breaks it.

The columns in the locked side have to be flexed to fit within instead of having a fixed width. So *if* the merged cells feature is present. column width setting must set the style like this:

```
column.flex = `1 1 ${width}px`;
```

So that the column *requests* its width, but flexes down if the space is not available. This requires the `ColumnResize` feature to have a setting which makes it set the width like this instead of using the `width` property.

The `MergeCells` feature will have to poke the `ColumnResize` feature to set this setting. And set the `overflow` of the merge column's subGrid.
