### ISSUE TITLE
Delimiter in number field localization problems

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6948]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=22727&p=125669#p125669)

Scenario 1

1. Open https://www.bryntum.com/products/grid/examples/localization/ Make sure English locale initially loaded. If not, change to English and reload the page.
2. Now change Age to decimal value, let's say "33.3". 
3. Change language to Svenska, where decimal delimiter is comma.

Actual result: See that delimiter stay same in the field.
Expected result: Delimiter should be changed to comma after locale change.

Scenario 2 
Open https://www.bryntum.com/products/grid/examples/localization/ with Svenska locale. There is a comma as delimiter in this locale. Try to type into number field decimal value "44,44". See that comma not interpreted as delimiter, like in English locale. Try to type "44.44" with dot. See dot is replaced to comma after editor closed.

Should be possible to type values as they are in current locale

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?f=43&t=27505&p=137702#p137702

**Comment by canonic-epicure** [comment]
The fix for this issue is to use the locale's configs for numbers, however it breaks the expectations of old test: `Core/tests/widget/NumberField.t.js//format config//default format should have no grouping or fraction constraints`

As discussed with Johan, removing that test and re-targeting the PR to the master branch.
