### ISSUE TITLE
Calendar inheritance does not work

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6997]
This calendar data yields cal 1 with no intervals.
```

"calendars" : {
    "rows" : [
      {
        "id"        : "general",
        "name"      : "General",
        "unspecifiedTimeIsWorking" : false,
        "intervals" : [
          {
              "recurrentStartDate" : "every weekday at 8:00",
              "recurrentEndDate"   : "every weekday at 17:00",
              "isWorking"          : true
          }
        ],
        "children" : [
          {
            "id"   : 1,
            "name" : "George",
            "intervals" : []
          }
        ]
      }
    ]
  },
```

**Comment by arcady-zherdev** [comment]
This happens because by default `unspecifiedTimeIsWorking` is `true`. So `George` calendar makes all the time frame working time plus it inherits root calendar intervals allowing some extra working periods which do not matter since all the time frame is already marked as working..

So if we set `George` calendar `unspecifiedTimeIsWorking` to `false` it will start working properly. Closing this.
