### ISSUE TITLE
`scrollEventIntoView` sometimes do not return a result to promise

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7197]
Test case:
[bryntum-event-selection-bug.zip](https://github.com/bryntum/support/files/12122564/bryntum-event-selection-bug.zip)

Video: 

https://github.com/bryntum/support/assets/7203098/18e81600-3f53-48cc-93e9-26584371c376

[Forum post](https://forum.bryntum.com/viewtopic.php?t=25280&start=20)

Here is a video of the workaround (from this forum), applied to the original demo code I provided.
I will also be attaching the demo with the workaround code for inspection.

You can see the bug is triggered fairly easily.

Bryntum scrolls to and selects a few events.
Then it does not perform the select. It even leaves the previous event selected, which you can see in the video.
There is a bug in the scrollEventIntoView in my opinion. The promise does not always resolve. And it does not reject with an error either.

I have explored awaiting scrollEventIntoView and using the Promise .then syntax.

We (as a team) are getting pretty desperate for this to work and be a reliable functionality.

**Comment by matsbryntse** [comment]
Easy to repro with
```

scheduler.scrollEventIntoView(scheduler.eventStore.first, {animate : {
                        easing   : 'easeFromTo',
                        duration : 5000
                    }})
```

and disturb the scroll by scrolling manually, the promise does not fulfil

**Comment by brokenthorn** [comment]
> and disturb the scroll by scrolling manually, the promise does not fulfil

Maybe because of the way the promise is coded to determine when it is fulfilled?

The browser scroll APIs seem to return Nothing when calling scrollTo. Perhaps Scheduler is continuously pooling if the frame is at the requested position and if something disturbed the scroll, that position never arrives and the promise never resolves?

This is what makes most sense to me (we see no rejection and resolving, right?).
