### ISSUE TITLE
Row selection should be fast

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7237]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=128105#p128105)

Hello,

I am running into a bit of an issue with the grid component when we encounter a large amount of rows. The grid currently has the ability to select all rows at the moment but this functionality seems to cause the page to stall with large amounts of data. As an example, the following code in the basic demo will cause a page delay: 

```
import { Grid, DataGenerator } from '../../build/grid.module.js?469543';
import shared from '../_shared/shared.module.js?469543';


new Grid({
    appendTo : 'container',
    selectionMode : {
        checkboxOnly: true,
        showCheckAll: true
    },
    columns : [
        {
            text  : 'Name',
            field : 'name',
        }
    ],

    data : DataGenerator.generateData(10000)
});
```
with even more rows causing more siginificant delays. It might also be worth mentioning that we didn't see this issue in Bryntum Grid version 5.1.0. I was wondering if you had any suggestions for working with a grid with this amount of data or more?

Thanks!
Connor

**Comment by ExtAnimal** [comment]
@JockeLindberg I think the issue is that in `prepareSelection`, `selectedRecords`, `deselectedRecords`, `selectedCellRecords`, `deselectedCellRecords` are all arrays that get multiply scanned using the `some` method.

They should be `Collections`, so that the following form can be used: `selectedRecords.contains(record.id)` 

Doing `Array.some` on a large record array causes the issue.
