### ISSUE TITLE
When task direction is set to Forward, constraint is ignored

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7301]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=25712)

Copy paste in here https://bryntum.com/products/gantt/examples/basic/
```
new Gantt({
    appendTo          : 'container',
    dependencyIdField : 'sequenceNumber',

tasks : [
    {
        "cls": "",
        "effort": 24,
        "calendar": null,
        "duration": 8,
        "inactive": null,
        "segments": null,
        "baselines": [],
        "direction": "Forward",
        "effortUnit": "hour",
        "parentIndex": 1,
        "unscheduled": false,
        "durationUnit": "day",
        "effortDriven": false,
        "constraintDate": "2023-07-31T16:00:00.000Z",
        "constraintType": "startnoearlierthan",
        "schedulingMode": "Normal",
        "manuallyScheduled": false,
        "confirmationStatus": null,
        "ignoreResourceCalendar": null,
        "id": "clkl5iw580003pkzmpqte4l7e",
        "name": "New task 2 Forward",
        "parentId": null,
        "startDate": "2023-07-31T00:00:00.000Z",
        "endDate": "2023-08-10T00:00:00.000Z",
        "confirmationReason": null,
        "description": "",
        "percentDone": "100",
        "children": []
      }
],
// project : {
    // autoLoad  : true,
    // transport : {
    //     load : {
    //         url : '../_datasets/launch-saas.json'
    //     }
    // }
// },

columns : [
    { type : 'name', width : 250 },
    { type : 'constrainttype', width : 250 }
],

// Custom task content, display task name on child tasks
taskRenderer({ taskRecord }) {
    if (taskRecord.isLeaf && !taskRecord.isMilestone) {
        return StringHelper.encodeHtml(taskRecord.name);
    }
}
});
```

See that task Constraint type is "as soon as possible", but correct value is "start no earlier than", see data. 
Now remove "direction" field from task's data. See now constraint is correct.

**Comment by canonic-epicure** [comment]
Since 5.4.0 the event's scheduling [direction](https://bryntum.com/products/gantt/docs/api/Gantt/model/TaskModel#field-direction) can be set on per-task level. Many users wants this feature to work identically to the MSProject implementation, where the scheduling direction for some reason is specified as an extra constraint type. So by default, we follow the same approach.

However, in this "compatibility" mode, the value of direction field overwrites the value of constraintType - its not possible to have both direction and regular constraint set on event.

To disable the compatibility mode, you can set the [includeAsapAlapAsConstraints](https://bryntum.com/products/gantt/docs/api/Gantt/model/ProjectModel#config-includeAsapAlapAsConstraints) project's config to false
