### ISSUE TITLE
Changing on end date is not working when workdays are enabled

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7350]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25966&p=129335#p129335)

"Hi,
On Basic Gantt chart demo, the isWorking is enabled which calculate the Duration excluding the Saturday and Sunday.
But when we change the end date the duration is getting calculated correctly but the end date is changed after we tab out of the field.
Eg:
Using the code editor include the startdate, enddate and duration column.
on the Task : 'Install Apache' modify the End date and set it to Jan 21, 2019. Due to this the days are displayed as 5(working days) but when we tab out of the End Date field, the value is changed from Jan 21. 2019 to Jan 19, 2019( which is a Saturday)"

https://github.com/bryntum/support/assets/16693227/13fcdf07-c445-4740-8034-2136e5ce1510

In the Basic Gantt demo, add the following columns and edit like the video

```
 columns : [
        { type : 'name', width : 250 },
{ type : 'startdate', width : 250 },
{ type : 'enddate', width : 250 },
{ type : 'duration', width : 250 }

    ],
```

**Comment by arcady-zherdev** [comment]
This is by design. Task start/end dates skip non-working time. When you selected 21th of Jan you provided `2019-01-21 00:00` to the end date ..which matched the end of non-working period of time starting at Sat 00:00 and ending Mon 00:00. So this non-working time got skipped backwards and resulted `2019-01-19 00:00`.
