### ISSUE TITLE
[REACT] renderer should react on REACT state changes

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7747]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26612&p=133205#p133205)

https://github.com/bryntum/support/assets/75997756/0adf63bb-98e8-4168-b8a7-b3cea6aac92c

[Another reported here](https://forum.bryntum.com/viewtopic.php?f=44&t=26792&p=133894#p133894)

This is reproducible with the demo below
[event renderer demo.zip](https://github.com/bryntum/support/files/13266587/event.renderer.demo.zip)

Video of reproduction

https://github.com/bryntum/support/assets/75997756/3e633c74-ae2f-4a68-97dd-938feea2ecb1

**Comment by abubakar-sarwar** [comment]
You should inspect the div element and see if the color and classname is changing or not, because state is working fine.

**Comment by jsakalos** [comment]
This is not a bug in fact. The problem here is that React portals containing JSX renderers are created from within the vanilla javascript so they are not aware of the "parent" React component so the React "state link" does not exist. 

The remedy is very easy: Use a "global" state manager. It can be Redux, if the application uses it, or it can be React Context. The new React demo "Using React Context with renderers" shows how to implement a very simple Context-based solution.

https://github.com/bryntum/bryntum-suite/pull/8180

**Comment by ghulamghousdev** [comment]
I have tested the solution without using any global state manager and it did not worked. I have also checked in the older versions to make sure that it shouldn't be something that is not breaking in the current version (versions checked 5.3.0, 5.4.0). Our demo with global state manager is out and please check it out here: https://bryntum.com/products/scheduler/examples/frameworks/react-vite/renderer-context/dist/
