### ISSUE TITLE
ResourceHistogram resourceCalendar intervals shows wrong on initial load

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7792]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26802&p=133769#p133769)

[resourcehistogram-interval-issue (1).zip](https://github.com/bryntum/support/files/13243751/resourcehistogram-interval-issue.1.zip)

Take a look at resources with the "custom" calendar which was modified. Take a look at the January 1 column - with the startDate and endDate that are set it has 8 hours (should be 0 as per calendar intervals configuration).
<img width="1690" alt="in initial view" src="https://github.com/bryntum/support/assets/7203098/a7d245d3-5816-4ec9-a8ed-902c2ec521aa">
But if you comment that startDate and endDate and uncomment those that are commented and click on arrows in the bottom toolbar to navigate forward to January 1 you'll see that in such case it has 0 hours.
<img width="1013" alt="not in initial view" src="https://github.com/bryntum/support/assets/7203098/1b876120-0b38-46c6-815d-0d56aa3182ba">

**Comment by arcady-zherdev** [comment]
Hello,
The reason of the reported behavior is both intervals have equal priorities so when the Engine sorts them sometimes wins one and sometimes another:
```js
{
    id                       : 'custom',
    name                     : 'Custom',
    unspecifiedTimeIsWorking : false,
    intervals                : [
        {
            recurrentStartDate : 'at 8:00 on monday, tuesday, wednesday, thursday, friday after 2020-02-06T22:00:00 before 2027-02-06T22:00:00',
            recurrentEndDate   : 'at 16:00 on monday, tuesday, wednesday, thursday, friday after 2020-02-06T22:00:00 before 2027-02-06T22:00:00',
            isWorking          : true
        },
        {
            recurrentStartDate : 'at 01:00 on the 1 day of January after 2020-02-06T22:00:00',
            recurrentEndDate   : 'at 01:00 on the 2 day of January after 2020-02-06T22:00:00',
            isWorking          : false
        }
    ]
}
```

Under the hood each interval has a priority value which is calculated automatically and depends on its type (recurring or static) and depth (if the calendar has parent calendar(s)).

And in this case the interval priorities are equal so the calendar does not know which one is more important. The `CalendarIntervalModel` has special `priority` field that allows to enforce the interval effect. It's not documented but should be fine to use.

You can just check what priority values are calculated by default and tweak them:
```js
// log interval priorities to console
calendar.getIntervals().forEach(interval => console.log(interval.recurrentStartDate, 'priority=', interval.getPriorityField()))
```
After you have the values just increase the value of the interval you want to enforce and put it in its `priority` field.

For example:
```js
        {
            recurrentStartDate : 'at 01:00 on the 1 day of January after 2020-02-06T22:00:00',
            recurrentEndDate   : 'at 01:00 on the 2 day of January after 2020-02-06T22:00:00',
            priority           : 10121,
            isWorking          : false
        }
```
The calendar will just use that value instead of calculating it.
Best regards,
Arcady
