### ISSUE TITLE
[REACT] React event renderer refreshes only first time

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#7861]
Steps to reproduce:

1. Navigate to https://bryntum.com/products/scheduler/examples/frameworks/react/javascript/react-events/build/
2. In console: `bryntum.query('scheduler').eventStore.first.name = 'Hello'` – the first event correctly refreshes.
3. In console: `bryntum.query('scheduler').eventStore.first.name = 'Hello World'` – the first event does not refresh.
4. No subsequent data changes refresh the UI.
5. Scrolling back and forth does refresh.

[Related forum post](https://forum.bryntum.com/viewtopic.php?p=134364#p134364)

**Comment by ghulamghousdev** [comment]
We have checked this issue and it is not reproducible on the latest release branch. We doubt that it got fixed in this ticket https://github.com/bryntum/support/issues/7891. So we are closing this ticket and the fix will be available in version 5.6.2.


https://github.com/bryntum/support/assets/52177956/92e6e784-dd19-462f-a75c-6c9131da6334
