### ISSUE TITLE
Adding a new event via `applyChangeSet` triggers auto sync

### ISSUE THREAD

**Issue by isglass** [bryntum/support#7889]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26942&p=134608#p134608)

Applying a changeset should probably not, and probably it should not even lead to stores being dirty. Or if implementer feels that is a too risky change of behavior, we could have a config for it or an argument to `applyChangeset()`

**Comment by matsbryntse** [comment]
Test + initial work in 7889-applyChangeSet

**Comment by bmblb** [comment]
related PR created a problem which was spotted by another client in a ticket #8263. Test logic is not bulletprrof - only change is a duration field and duration field is supposed to be calculated and persisted. Test can be fixed by simply providing a duration field. Or marking duration field as `persist: false`. Meaning there is an easy solution on the application level.

I asked for more details in the related forum post. In the meantime old behavior should be brought back
