### ISSUE TITLE
Add event recurrence support to Scheduler Pro

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#792]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21405&p=106868#p106868)

**Comment by dongryphon** [comment]
It seems that `RecurringTimeSpan` is not a base for `TaskModel`... so is there some kind of field detection needed to know if the task being edited supports recurrence?

**Comment by dongryphon** [comment]
From Johan:

> Only valid for Scheduler Pro, it uses events but with TaskEditor. Adding to SchedulerGeneralTab.js would make it appear only in Scheduler Pro

**Comment by dongryphon** [comment]
I'm putting this back in case someone is looking for stuff while I look at a new one more in my wheelhouse (https://github.com/bryntum/support/issues/2127)

**Comment by dongryphon** [comment]
As I looked into how Calendar handled event edit w/recurrence, the edit feature has various pieces related to recurrence. There is a lot more going on there than just the form fields and calls to confirm "this event or the whole series"

**Comment by fabiojpoli** [comment]
That's right @dongryphon . There are some work in progress on branch based on master. I have created new mixin to scheduler and scheduler pro mixins extend it to use same function but there are still many things to do.

**Comment by fabiojpoli** [comment]
Work in progress:
At the branch `792-add-recurrence-fields-taskeditor` was created a new generic mixin  about recurrence (`Scheduler/feature/mixin/RecurringEdit.js`) where Scheduler and Scheduler Pro recurrence mixins (`Scheduler/feature/mixin/RecurringEventEdit.js` and `SchedulerPro/feature/mixin/ProRecurringEventEdit.js`) extends it, there are some things to do on Scheduler Pro:

- `onRecurrableEventBeforeDelete` and `onRecurrableEventBeforeSave` handled on events `beforeEventDelete` and `beforeEventSave` has the parameter context to work with the promise, used to work with modal confirmations alerts, but Scheduler Pro doesn't have it for both events, should be adapted.
- Line `editor.widgetMap.editRecurrenceButton.menu = me.recurrenceEditor` was commented out because on click save on SchedulerPro there is no action when this line is there, should debug to identify the problem.
- There are another points to be implemente and make it work, to check what is not working yet, was adapted all tests about Recurrence on Scheduler to SchedulerPro (11 files, ~70 tests) to be easy to identify the current functionalities not working for this feature based on tests fails.

**Comment by fabiojpoli** [comment]
Feature implemented but there are some fails on tests.

**Comment by arcady-zherdev** [comment]
Adding fields to the task editor is not a problem here. The feature is not done on the data level.
Problems that should be addressed:

- calendars should be taken into account
- occurrences should probably be stored in the graph (?)

**Comment by arcady-zherdev** [comment]
event recurrence functionality for scheduler pro was requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=17449
