### ISSUE TITLE
PDF Export event bars not correctly rendered when dependencies enabled

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7929]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27085&p=135254#p135254)

https://bryntum.com/products/scheduler/examples/export/

Enable dependencies feature using a button on a tbar, export to PDF. 
See PDF has no event bars rendered
<img width="836" alt="Screenshot 2023-11-28 at 10 55 57" src="https://github.com/bryntum/support/assets/7203098/923eaa49-5a31-431e-9dae-f7daa02b7dac">

**Comment by chuckn0rris** [comment]
Another report https://forum.bryntum.com/viewtopic.php?f=52&t=27157&p=135565#p135565

**Comment by bmblb** [comment]
Apparently, this issue is caused by puppeteer not being able to apply width style to `b-sch-foreground-canvas` element. Recently there was an update which changed its width to:
```
.b-sch-canvas {
    width: max(var(--total-column-width, 100%),100%);
}
```

Workaround is simple enough: width should be set to 100%. Either using application CSS or changing config of the export feature to add extra style:
```
```
features : {
  pdfExport : {
    filterStyles : s => [...s, '<style>.b-sch-foreground-canvas { width: 100% !important; }</style>']
  }
}
```
