### ISSUE TITLE
Localization upgrade guide for v5.3 has wrong code snippets

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7941]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=26493&start=10)

Here wrong code snippets https://bryntum.com/products/gantt/docs/guide/Gantt/upgrades/5.3.0
Here correct versions https://bryntum.com/products/scheduler/docs/guide/Scheduler/customization/localization#extend-existing-locale

Check for all products

**Comment by ghulamghousdev** [comment]
I have checked this issue and our documentation is correct. The actual issue was in user's code. He was trying to apply the locale in the following manner:
```
LocaleManager.applyLocale({
    localeName : 'En',
    localeDesc : 'English (US)',
    localeCode : 'en-US',
    myLocale
});
```

The above code resulted in the `nameOfConfig` in `applyLocale` to:
```
nameOrConfig ={
    localeName : 'En',
    localeDesc : 'English (US)',
    localeCode : 'en-US',
    myLocale : myLocale
}
```

But our implementation expects the `nameOrConfig` parameter in `applyLocale` to be in the following manner:
```
nameOrConfig ={
    localeName : 'En',
    localeDesc : 'English (US)',
    localeCode : 'en-US',
    locale : myLocale
}
```

More specifically it expects `locale` key in the config object that in users case wasn't present. Changing the users code to below worked:
```
LocaleManager.applyLocale({
    localeName : 'En',
    localeDesc : 'English (US)',
    localeCode : 'en-US',
    locale: myLocale
});
```

So I am closing this ticket as completed as there was no issue in our current documentation.
