### ISSUE TITLE
Elevate `tabIndex` config from TextField to Field

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8010]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27228&p=135973#p135973)

The `tabIndex` configuration must be in the Field class, not in the TextField class. Because all input elements have the tab index attribute!

**Comment by ExtAnimal** [comment]
`DateTime` field will have to use tabIndex and tabIndex+1 since it contains two nous fields.

**Comment by henriquewerlang** [comment]
Theoretically, the tabindex of DateTime field, must be of the container of the fields and the internal tabindex must be 0 and 1, respectively.

**Comment by henriquewerlang** [comment]
Reading the Mozzila documentation, any element can have the "TabIndex" attribute, with this info, I guess this configuration must be moved to the Widget class.

**Comment by dongryphon** [comment]
Moving this to `Widget` makes sense but will present some special case issues: imagine assigning it to a `Calendar` or a `Scheduler` or `Grid`. While these makes no sense, it is still correct for many cases.

As for compound widgets like `DateTime`, one must set the same `tabIndex` on all relevant focusable elements or you'll get surprising behavior. See [CodePen](https://codepen.io/dongryphon/pen/yLwYLaP):

```html
<html>
  <body>
    <input type=text tabindex="0" value="First (tabIndex=0)"></input>
    <input type=text tabindex="1" value="Second (tabIndex=1)"></input>
    <input type=text tabindex="0" value="Third (tabIndex=0)"></input>
    <input type=text tabindex="0" value="Fourth (tabIndex=0)"></input>
    <input type=text tabindex="1" value="Fifth (tabIndex=1)"</input>
  </body>
</html>
```

https://github.com/bryntum/support/assets/722969/c0b9581d-273b-4af8-bf5b-632707703917

There are good reasons why MDN [warns against](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) assigning `tabIndex` to anything other than `0` and `-1`.

**Comment by dongryphon** [comment]
There are a lot of complexities in hoisting this to `Widget` due to the complex rendering in many advanced components and the fact that so many are not focusable themselves but contain a number of focusable elements. It is not clear what `Widget` can really offer as a baseline meaning for this config because it is not clear the element(s) to which it should be applied (if any).

Without a clear use case for when to ignore the general pattern of 0/-1, it seems best to hoist `tabIndex` to `Field` as originally requested and do minimal work propagating its value.

For example, `DateTime` could be configured like so:
```javascript
    {
        type : 'datetimefield',
        tabIndex : 1
    }
```

and that would be equivalent to:

```javascript
    {
        type : 'datetimefield',
        dateField : { tabIndex : 1 },
        timeField : { tabIndex : 1 }
    }
```
