### ISSUE TITLE
Event is re-rendered when drag starts

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8159]
http://lh/bryntum-suite/calendar/examples/resource-avatars/

triggering extra resource request

https://github.com/bryntum/support/assets/218570/dfe3d399-d8d4-4af4-9a8c-e03172aa2403

**Comment by dongryphon** [comment]
The Network row is generated because of the drag proxy:

![image](https://github.com/bryntum/support/assets/722969/83799a30-e56c-4d45-9043-49e3ee43d596)

The markup just has an `<img>` element with the `src` attribute:

![image](https://github.com/bryntum/support/assets/722969/becb48d3-c48d-491b-9c5a-61a997ce0726)

**Comment by dongryphon** [comment]
In fact, it is the "Disable cache" setting that forces the request to be sent. If I turn OFF this setting, no request is sent:

![image](https://github.com/bryntum/support/assets/722969/c1b25f0b-4d60-4161-864c-727dfadc85bf)
