### ISSUE TITLE
[REACT] App crashing/stuck when moving multiple events and some aren't in view

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8209]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27521&p=137775#p137775)

Hi,
We have an issue that when selecting multiple events, then scrolling so that one or more events are no longer visible/in view - the page crashes/gets stuck.
We are using version 5.6.3 but I have been able to successfully re-create this using one of your online demos using the latest version. 
 
The demo I used is - https://bryntum.com/products/schedulerpro/examples-scheduler/frameworks/react/javascript/react-events/build/.
This is the recording: 
https://github.com/bryntum/support/assets/7203098/51b36fa2-9dc4-48c9-9a2e-3fcc56caf60a

This is a screenshot of the error: ![Screenshot 2024-01-09 at 19.22.47.png](https://forum.bryntum.com/download/file.php?id=26068)

These are the exact steps:
Multi select two or more events
Scroll horizontally so that one of the events is no longer in view
Try dragging (by clicking on the visible event)

=> App crashes/ is stuck
Error appears in console (attached above).

I would appreciate it if you could look into this issue immediately and resolve it as soon as possible.
Thanks,
Odiya Erlichster
![Screenshot 2024-01-09 at 19.22.47.png](https://forum.bryntum.com/download/file.php?id=26068)

**Comment by canonic-epicure** [comment]
Made a brief check with the following results:
- exception is thrown in the `addTemporaryDragElement` of `HorizontalRendering.js`, which is called with the unusual `domConfig` argument, I guess containing unresolved react JSX element
- this is probably because the demo uses react JSX renderer for event

This is not my area of expertise, perhaps @jsakalos can investigate?

![image](https://github.com/bryntum/support/assets/72431/05d340e4-d8ba-4d99-86f6-c785d9ffb11e)
