### ISSUE TITLE
Grid vue demos are not compatible with IE11 and Trial bundle

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#821]
These demos are not compatible with IE11 and obfuscated Trial bundle.
But they seem to work with full bundle only.
```
Grid\examples\vue\javascript\advancedgrid\
Grid\examples\vue\javascript\columntypes\
Grid\examples\vue\javascript\dashboard\
```

Demo does't start with 
```
SCRIPT5022: exception thrown but not caught
inherits.js (7,5)
```

Testing disabled for IE11. Restore it when issue is resolved.

**Comment by jsakalos** [comment]
This issue is probably caused by the fact that:
```
typeof HTMLElement // returns "object" in IE 11
typeof HTMLElement // returns "function" in other browsers
```
The above script `inherits.js` checks type of the passed arguments to be a function but it throws on our `GridTag` that extends `HTMLElement` so the check of type fails.

I haven't found the reason why it does not fail in non-trial examples. Non-trials work in IE 11 OOTB.

**Comment by SergeyMaltsev** [comment]
Checked in `npm` project branch.
Vue trial demos work in IE11
