### ISSUE TITLE
Panel fields items not being populated from record config

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8328]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=138848#p138848)

Hello, Team!

I have noticed that the record config works for Container (meaning it populates field values based on record), but not for Panel. Is this expected? Panel extends Container and I guess it should work the same.

Sample code:

```
const record = new Model({
	firstName: 'John',
	lastName: 'Smith',
});

const items = {
	firstName: {
		type: 'textfield',
		name: 'firstName',
		label: 'First Name',
	},
	lastName: {
		type: 'textfield',
		name: 'lastName',
		label: 'Last Name',
	},
};

new Panel({
	appendTo: document.body,
	record,
	items,
});

new Container({
	appendTo: document.body,
	record,
	items,
});

```

**Comment by scebotari66** [comment]
The root cause is in the `childItems` getter. The Container references `this.items` in the getter, whereas the Panel references `this._items`, which is not yet initialized when `updateRecord` is called.

Not sure if this needs fixing. It will work for the Panel if you declare the `items` config before the `record`, like so:
```js
new Panel({
  appendTo: document.body,
  items,
  record,
});
```
