### ISSUE TITLE
Add ability to assign more than 100% of a resource

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#833]
A resource could have its maximum capacity attribute. In order to set it for example to 500% to a team of five people. Need to make sure the resource histogram takes this config into account and doesn't treat such resources as overallocated.

Was requested here: https://www.bryntum.com/forum/viewtopic.php?p=72682

TODO:
- [x] Update scale column for individual resources?
- [x] Update maxEffort line for individual resources?
- [x] check/fix/close #4396

**Comment by christos-ts** [comment]
Hi, this is a major improvement for construction companies using subcontractors because we only plan for the subcontractor himself and not his team members. This is done in MS Project by setting the units to more than 100%.
As a consequence in Team Planner (aka Resource utilization/histogram) overallocation for this resource happens not in 100%.
Is there any chance you get this request to your roadmap soon?
Many thanks

**Comment by matsbryntse** [comment]
@christos-ts We hope to start working on this in Q3 - if you need it sooner, we could discuss a feature sponsorship too. Feel free to reach out to sales [at] bryntum if interested.

**Comment by christos-ts** [comment]
@matsbryntse thank you very much for your prompt replies as always mats! We are looking forward to implementing this must-have feature.

**Comment by christos-ts** [comment]
@matsbryntse thank you very much for your prompt replies as always mats! We are looking forward to implementing this must-have feature.

**Comment by SafwanHak** [comment]
Hi, any news/solution/workaround for supporting resource capacity? Happy to beta-test this if you're working on it.

**Comment by christos-ts** [comment]
Hello! Any news on this one ?
Many thanks
Christos

**Comment by christos-ts** [comment]
Hello and happy holidays!
Have you got any news regarding this issue?
Thank you
