### ISSUE TITLE
Setting `duration` as `field` goes to infinity on edit

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8798]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28345&p=142441#p142441)

"Hello,
When editing duration in table it goes to infinity 
based on react profiler no re-reanders are happening 

here is a video of these
https://youtu.be/CBS-vATVFN0

there in nothing special configured on these columns 
and i tried commenting all of my custom setting. nothing helped 

```
            { field: "startDate", text: "Start", autoWidth: true, type: "startdate", format: 'DD.MM.YYYY' },
            { field: "endDate", text: "Finish", autoWidth: true, type: "enddate", format: 'DD.MM.YYYY' },
            { field: "duration", text: "Duration", autoWidth: true, type: "duration" },

```
"

Reproducible on https://bryntum.com/products/gantt/examples/basic/ by adding the duration column just like the user snippet.

https://github.com/bryntum/support/assets/16693227/3c4b7d9f-4167-446a-8eb9-cfb6070c27f4

**Comment by konstantinsp** [comment]
hello,
Tested on latest version 6.1.4
and in your basic example
bug still exists

**Comment by ghulamghousdev** [comment]
Hello @konstantinsp,

Are you setting `duration as field` on the duration column? if yes then it is not allowed, as you can see in the docs of field on durationColumn https://bryntum.com/products/gantt/docs/api/Scheduler/column/DurationColumn#config-field. Because the field needs both a duration magnitude and unit, as supplied by for example the [fullDuration](https://bryntum.com/products/gantt/docs/api/Scheduler/model/TimeSpan#field-fullDuration) field. 

<img width="776" alt="Screenshot 2024-12-16 at 5 59 31 PM" src="https://github.com/user-attachments/assets/c649600d-a348-42c1-829a-1d38993f816b" />
