### ISSUE TITLE
Error when slowly scrolling the Gantt

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9001]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28716&p=144551#p144551)

The user reported an error when slowly scrolling in the example with React (tried to reproduce in the advanced plain JS demo, but not reproducible).

Steps to reproduce:

- load the app with same data and config.

- loads successfully.

 - Slowly zoom in zoom out. (check console).

- you will get this error. (attached screenshot).

[recordingBryntum.webm](https://github.com/bryntum/support/assets/16693227/a78aeb0f-7d8a-45db-893a-b335c40d4177)
![Screenshot from 2024-04-15 22-32-56](https://github.com/bryntum/support/assets/16693227/4718be81-0f7a-4cf8-87c5-9481659bbc48)

[test-app-bryntum.zip](https://github.com/bryntum/support/files/14984328/test-app-bryntum.zip)

**Comment by jsakalos** [comment]
This is not React related but it is caused by `fillTicks: true` It can be reproduces by zooming in/out on vanilla basic demo with fillTicks set to true:
<img width="1567" alt="Screenshot 2024-04-16 at 10 13 56" src="https://github.com/bryntum/support/assets/204844/2ef52c70-d036-4024-8889-946ddac37385">
