### ISSUE TITLE
Grid printing does not handle auto height rows

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9198]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29058&p=146343#p146343)

"hello bryntum team
I'm currently working with the printing feature however I noticed some event data is cutting off, I thought this was an error on my code but reviewing your print demo on the agenda it has the same problem
how could I fix this ? I tried to add some media print queries however the result is the same

The second entry on the agenda list has 10 items
![Screenshot 2024-05-15 at 2.17.08 p.m..png](https://forum.bryntum.com/download/file.php?id=28422)

however in the print preview, the text is cutting off
![Screenshot 2024-05-15 at 2.18.34 p.m..png](https://forum.bryntum.com/download/file.php?id=28421)"

- Go to https://bryntum.com/products/calendar/examples/print/
- Try to print agenda mode
- The pdf generated is attached here
[Bryntum Calendar - Print demo.pdf](https://github.com/bryntum/support/files/15327189/Bryntum.Calendar.-.Print.demo.pdf)

**Comment by ExtAnimal** [comment]
The issue is that Grid printing does not handle auto row height.

Try printing the `/Grid/examples/autoheight/` demo.

You have to add

```
import '../../lib/Grid/feature/export/Print.js';
```

Then run `grid.print()`:

![Screenshot 2024-05-16 at 10 07 26](https://github.com/bryntum/support/assets/200516/11667c91-ffcd-46f1-87d8-0825dcb7b4b8)

`grid.columns.usesAutoHeight` reports `true` if any columns are `autoHeight`. *But*, it checks *all* columns, so if `autoHeight` columns are hidden, it will still report `true`.

See if fixing that causes problems. It's unlikely that some usages require it to return `true` if there are no *visible* auto height columns.

**Comment by ExtAnimal** [comment]
`fakeRow` which is used to create the rows for printing must be added as a child to its owning `SubGrid` body element so that

1. It has layout and can be measured.
2. It gets the CSS styles that the app expects to be applied to the grid;

**Comment by ExtAnimal** [comment]
`Exporter`'s `restoreState` is what causes a refresh of the real Grid while `isExporting is set to `true`.

`restoreState` needs

```
client.isExporting = false;
client.state = this.state;
```

So that any renderers intended to create special, print-only output do not get called when the grid is refreshed by having its state restored.

**Comment by ExtAnimal** [comment]
See also this Grid Print issue: https://github.com/bryntum/support/issues/9295
