### ISSUE TITLE
Maximum Fraction digits format for NumberField with strange behavior when using a large number

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9328]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=29274&p=147713#p147713)

"Hi Team,
We have configured a NumberField with format maximumFractionDigits: 9, in order to limit the number of fraction digits that can be entered. When working with big numbers this seems not to be working properly.
Entering an integer big number, following by dot (decimal separator)  and decimal digits, the number seems to be loosing fractional part when inserting more than 9 digits.
I have attached a video showing this behavior. Could you please take a look?"

- Using the following snippet:
```
new NumberField({
    appendTo : document.body,
    width    : 200,
    label    : 'Enter a number',
    style    : 'margin-right: .5em',
   format: { maximumFractionDigits: 9 }
});
```

If you test a number like `1,123456789` it'll work correctly, but when using a big number before the comma, like `123456789123456789,123456789` it'll show a different number.

https://github.com/bryntum/support/assets/16693227/63e338c8-ff54-4ece-9a77-4f17bd08fc51

**Comment by dongryphon** [comment]
The issue is the numeric limits of a JS Number. A number in JS can only hold 15-17 digits of precision. The example number of `123456789123456789.xxx` starts with 18 digits before the decimal, and so the least significant digits will be lost. That is, all of the fractional part and even a few non-fractional digits.

See [the MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) for more details.
