### ISSUE TITLE
useRawData set in TaskStore makes gantt crash when re-rendering

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9367]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=29353&p=148227#p148227)

![Bryntum-2024-06-11-006.png](https://forum.bryntum.com/download/file.php?id=28991)

In the example provided by the user, when using useRawData: true config, the Gantt crashes when a re-render is triggered. That's not reproducible on Vanilla JS, only on React.

[Bryntum-2024-06-11-006-2.zip](https://github.com/user-attachments/files/15794776/Bryntum-2024-06-11-006-2.zip)

**Comment by jsakalos** [comment]
The root cause here is that when `useRawData` is `true` it 
> pollutes the incoming data 

as written in https://bryntum.com/products/gantt/docs/api/Core/data/Store#config-useRawData

Explanation:
1. The BryntumGantt is created first time using imported `ganttConfig` object which also contains data.
2. The data is "polluted", i. e. replaced by the instances of records, replacing values with calculated ones, etc. as needed
3. The BryntumGantt is destroyed which means the component and its stores are fully destroyed, however, data is not. It remains in the mutated version in `ganttConfig` (import only occurs once)
4. The BryntumGantt is re-created with already invalid (or potentially invalid) input data so it crashes.

Now, there are several question to the application author:

1. What is to be achieved with creating and subsequent destroying the Gantt? If it is to update the data, another method should be used, such as binding reactive properties of `project` to the data source. Virtually all more advanced Gantt React examples show this approach. If a change of appearance should be achieved, it can also be done with reactive properties. Re-creating the component is the very worst method of achieving the above.
2. Why to use `useRawData` in the first place? It is a flag that should only be used in very special circumstances, sure not in a common React app. If the React app held data in it's state or in redux, this flag would case mutating this data without React/redux knowing about that. This can lead to unpredictable behavior and hard-to-find bugs in the app.

If there are real reason for re-creating and `useRawData`, then the following resolves the issue (in `App.tsx`):
```
import { ObjectHelper } from '@bryntum/gantt';
import { ganttConfig } from './AppConfig';

const App: FunctionComponent = () => {
    const [isTrue, setIsTrue] = useState(false);

    const config = ObjectHelper.clone(ganttConfig);

    return (
        <Fragment>
            <button onClick={() => { setIsTrue(!isTrue); }} style={{ margin: "2em", width: "10em" }}>Re-render</button>
            <BryntumGantt key={isTrue + ""} {...config} ref={(ref) => {
                (window as any).gantt = ref;
            }} />
        </Fragment>
    );
};

```

This way we always supply `BryntumGantt` with a fresh new `ganttConfig` so it always works as the first time.

**Comment by FlowIT-JIT** [comment]
Thank you for helping us identify the problem @jsakalos 👍
