### ISSUE TITLE
[REACT] Drop Artifacts Created When constrainDragToTimeline is false

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#9383]
Yes, it behaves as user explains. The React code seems clean so it might not be a bug in wrappers.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=29374&p=148343#p148343)

![drag-and-drop-bug.gif](https://forum.bryntum.com/download/file.php?id=29024)

Source code / test case example attached.  Steps to reproduce:
npm install
npm run start
Start dragging and holding an event element

We identified a problem on our scheduler board when an event element is dragged and held. The issue arises if the event is moved again while an update is in progress. The element continues to display incorrectly, even though it should not. The root cause is unclear, but resolving it is essential as dragging functionality within and outside the grid is necessary. It appears to be a race condition that results in an artifact when a server update coincides with the dragging action.
![drag-and-drop-bug.gif](https://forum.bryntum.com/download/file.php?id=29024)

**Comment by omnisip** [comment]
Any update on this?

**Comment by ghulamghousdev** [comment]
Hi @omnisip,

I have debugged this issue and it turns out to be an issue with how you have configured the `project` on `schedulerPro` component. You were directly passing the `project` to the `schedulerPro` which is not a recommended way and is creating a new `project instance` on each `re-render` caused by the `useGetEventsQuery` hook. We recommend to use `BryntumSchedulerProProjectModel` or use `useState` hook to manage the project config and pass the project variable to `schedulerPro` component.

### Approach 1:

Declare a ref for project:
```
const projectRef = useRef();
```

Now use BryntumSchedulerProProjectModel:

```
        <BryntumSchedulerProProjectModel 
            ref={projectRef}
            events={events}
            resources={resources}
        />

// do not pass the assignments as you have already used resourceId on events
```

and now pass the projectRef to the SchedulerProComponent:
```
        <BryntumSchedulerPro
            project={projectRef}
            ref={schedulerPro}
       />
```

### Approach 2:

Place the project config inside a useState variable:

```
const [project, setProject] = useState({ events, resources});
```

Pass it to the schedulerPro component:

```
        <BryntumSchedulerPro
            project={project}
            ref={schedulerPro}
       />
```

And everything works great. We have a docs section here on how to configure things: https://bryntum.com/products/schedulerpro/docs/guide/SchedulerPro/integration/react/guide#best-practices-for-configuration-management

Updated Project: 
[Drag_Artifacts-Project.zip](https://github.com/user-attachments/files/16252745/Drag_Artifacts-Project.zip)


https://github.com/user-attachments/assets/81350b07-0abd-4606-b275-239b4e66e0c2

**Comment by omnisip** [comment]
- When we reviewed the link you sent, we found it missing information on the ProjectModel or the useState proposals you're listing above.  
- When we prepared the test code for you, we were trying to reproduce the issue in the smallest possible format.  In our actual code, we instantiate the project like this:

![image](https://github.com/user-attachments/assets/edb241bb-1ff6-4b44-85fb-382cddbea173)

Unfortunately this is not a direct drop in replacement with BryntumSchedulerProProjectModel.  

If we try to set the assignmentStore on the BryntumSchedulerProProjectModel we get an error like this:

![image](https://github.com/user-attachments/assets/c5018962-97d5-4e17-a41a-9179156d57ff)

Adding it directly to the BryntumSchedulerPro instance instead doesn't seem to resolve the issue either.

Trying with useState isn't a practical option for us because we use redux and storing instances of classes or functions in the redux store is bad practice and will generate lots of warnings.

**Comment by omnisip** [comment]
Versions tested: 5.6.13 and 5.6.10

**Comment by ghulamghousdev** [comment]
Using `BryntumSchedulerProProjectModel` should not throw any error because this is the recommended way of setting up project on schedulerPro component. We have confirmed that it is not an issue on our end. But we will be happy to assist you in setting up the project in correct way in your project and help you out to get rid of any issues. If possible can you please share your implementation of the project with minimum code for project setup with us. I can understand, that you may have privacy concerns so you can share it on email: support@bryntum.com.

**Comment by omnisip** [comment]
When we add 
                assignmentStore={{
                    onRemove: (event) => console.log(event),
                }}


to the 'BryntumSchedulerProProjectModel' and start the project we see an empty page and a console has errors.

This appears to happen in v5.6.10 and v6.0.1

[Drag_Artifacts-Project - assignmentStore -issue.zip](https://github.com/user-attachments/files/16286495/Drag_Artifacts-Project.-.assignmentStore.-issue.zip)

**Comment by ghulamghousdev** [comment]
@omnisip Thanks for providing the testcase and I will check it out in couple of hours and let's see how things go. I will update you accordingly. Please don't worry, we are here to help and will resolve the issue if it is on our end.

**Comment by ghulamghousdev** [comment]
Hi @omnisip,

I got the time to check your test case and it turned out to be another issue with your project management. I forgot to mention that any configs used in `BryntumSchedulerProProjectModel` should be wrapped inside a useState or should be imported from a static file. We have a guide about it here: https://bryntum.com/products/schedulerpro/docs/guide/SchedulerPro/integration/react/data-binding#binding-existing-data-to-the-project. So changing your config to this solved the issue. The reason is, when you are defining an assignmentStore directly on ProjectModel, it has been recreated each time component is rerendered. Please adopt to the following approach:

```
  const [projectConfig] = useState({
    assignmentStore: {
      onRemove: (event) => console.log(event),
    },
  });
```

```
      <BryntumSchedulerProProjectModel
        ref={projectRef}
        resources={resources}
        events={allEvents}
        {...projectConfig}
      />
```

Please make sure all the project configs should be wrapped in a useState or imported from a static file. Another important thing is how you are updating the data after polling. We suggest using the https://bryntum.com/products/gantt/docs/api/Gantt/model/ProjectModel#function-loadInlineData. Please let me know if you guys face any other issue. Happy to assist.
