### ISSUE TITLE
Tooltip slides into view after collapsing example code editor

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9694]
https://bryntum.com/products/gantt/examples/summary/

https://github.com/user-attachments/assets/1afcd631-6c9a-48f0-9261-0faaf9ba711a

**Comment by ExtAnimal** [comment]
Needs this CSS in `widget.scss`:

```
.b-realigning {
    width : max-content;
}
```

The issue is that the widget was narrow, and aligned to the right edge of the screen. When it gets large, new content, and is shown, then because it's up against the right edge of the screen, it constrains its own width. Adding the `width : max-content` when realigning will let it expand to its natural width before doing the realign.

**Comment by ExtAnimal** [comment]
Just needs `me.x = 0;` at the start of `alignTo` to allow the widget to regain its natural width if it was aligned up against the right edge of the viewport.
