### ISSUE TITLE
beforeEventDropFinalize should include new startDate/endDate values of the dragged event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9795]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=152536#p152536)

No way to know when the event is being scheduled in the listener. The startDate/endDate params are present, just need docs / tests.

**Comment by ExtAnimal** [comment]
This is a docs app issue. All the data is available and documented. The docs app just doesn't link up very well.

`DropData` is defined which also links to ` typedef. But because the section in which the user is clicking collapses, the scroll into view of the linked-to typedef fails.

<img width="786" alt="Screenshot 2024-08-12 at 10 03 05" src="https://github.com/user-attachments/assets/b54ddd52-8346-436a-a174-34f364426404">
