### ISSUE TITLE
Non-working intervals are calculated incorrectly in certain time zone

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#9798]
Reported here: https://forum.bryntum.com/viewtopic.php?f=52&t=30056&p=152506#p152506
And similar case is here: https://forum.bryntum.com/viewtopic.php?p=153197#p153197

Steps to reproduce:
1. use this dataset with gantt advanced demo: [launch-saas.json](https://github.com/user-attachments/files/16579269/launch-saas.json)
2. in `app.js` comment out view start/end dates
3. set system time zone to Cairo time

Run the demo and see a number of console errors
![image](https://github.com/user-attachments/assets/e176dbe8-d465-43a7-aafa-f2d54b2a1339)

**Comment by bmblb** [comment]
upd: also set `hoursPerDay` to 9

**Comment by ghulamghousdev** [comment]
+1 here: https://forum.bryntum.com/viewtopic.php?p=154174#p154174

**Comment by arcady-zherdev** [comment]
The reason of the issue is too strictly specified intervals which ignore the DST change rules for that timezone.
```js
    "recurrentStartDate" : "on Fri at 0:00",
```

There rule didn't match Friday 26 of April 2024 since the on that date/time DST was enabled so effectively there was `01:00` of the next day instead of `00:00`. And thus LaterJS doesn't match that date which results calendar code confusing ..intervals open and close attempts didn't match.

I'll add a warning to calendars docs and change the code to handle this a bit nicer. But there isn't that much we can do here the intervals provided are incorrect considering the timezone.
