### ISSUE TITLE
Support for UUID version 7

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9831]
https://www.npmjs.com/package/uuidv7

**Comment by maartenraes** [comment]
Additonal context about the feature request; 

Request driven by the timestamp component that makes indexing easier and nice indexing. Can also be used as database ID, which saves a round trip to the database if you want to create and then immediately patch the entity

However, [docs suggest that Phantom ID's should not be persisted](https://bryntum.com/products/gantt/docs/guide/Gantt/data/crud_manager_project#sync-request-structure), so this might collide with this request, since it is the ambition to save these Phantom ID's to the database. 

> Please do not persist phantom record identifiers as-is on the server. That might cause collisions on the client after data reloading. It’s expected that backend assigns new identifiers to added records.

Since they're UUID's, I don't see an issue with saving them to the database, since multiple clients will never collide, and multiple tasks from the same client should also never collide.

**Comment by isglass** [comment]
- [ ] The `static generateId()` fn in `Model.js` needs to be made public by adding docs to it.
- [ ] Add test coverage to `ModelIdField.t.js`

Be aware that generating UUIDs currently has a fairly big impact on performance, but as long as existing records have one assigned from the backend presumably the impact wont be big.
