### ISSUE TITLE
CalendarEditor can't remember new week setting

### ISSUE THREAD

**Issue by NegativeDearc** [bryntum/support#9943]
Reproduce steps

1. Create default week from calendar editor
2. Create new week
3. Change new week setting and save
4. Re-open, you'll see the settings changed

Test from: [https://bryntum.com/products/schedulerpro/examples/calendar-editor/](https://bryntum.com/products/schedulerpro/examples/calendar-editor/)

add new column
```
        {
            type    : 'resourceCalendar',
            text    : 'Calendar2',
            width   : 180,
            calendarEditor: {
              removeButton: false,
              parentField: false,
              activeDate: new Date(),
              width: 900,
              defaultWorkingDays : {
                0 : true,
                1 : true,
                2 : true,
                3 : true,
                4 : true,
                5 : true,
                6 : true
              },
              defaultWorkingDayAvailability : [
                { startDate: '08:00', endDate: '20:00' },
              ],
              listeners : {
                catchAll : (event) => {
                  console.log(event);
                }
              }
            }
        }
```

**Comment by arcady-zherdev** [comment]
I couldn't reproduce the issue.

> 1. Create default week from calendar editor
Create default week for which calendar? All calendars in that demo have default weeks specified.

> 2. Create new week
> 3. Change new week setting and save
What changes exactly should I do?
> 4. Re-open, you'll see the settings changed

All worked fine here. Since you haven't provided exact steps I tried this scenario:

1 . Added a new resource w/o `calendar` field specified.
2. Started resource calendar column cell editing for the resource.
3. Clicked the cell editor trigger icon to show the calendar editor 
4. opened `Weeks` tab
5. added a default week
6. added one more week
7. removed some days time ranges and clicked `Save`
8. finished cell editing
9. started the column cell editing again
10. clicked the trigger again
11. opened `Weeks` tab

Result: all changes made were there

**Comment by NegativeDearc** [comment]
Uploading calendarEditorCantSaveWeekSettings.mp4…

See videos

**Comment by arcady-zherdev** [comment]
@NegativeDearc reproduced now. thank you for details!

**Comment by NegativeDearc** [comment]
Another way to make this happen

in weeks tab if you split time eg. 08:00 - 00:00 to 08:00- 20:00 and 20:00 to 00: 00 will also make this happen

![image](https://github.com/user-attachments/assets/3d379198-2da1-466b-9f62-a1b9cd9fdb4f)

I think this problem is very critical that impact the user experience.
