### ISSUE TITLE
Allow `showOn : 'click'` event tooltips to show on a delay after the click

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#9971]
/calendar/examples/travel-time/

When you click on an event element a popup appears. If you double click event element, first the popup appears, then immediately disaapears as event editor shows up. It looks like a blink

**Comment by ExtAnimal** [comment]
Noting to do with styling.

The only way round this is to show the event tooltip on an annoying timer which gets canceled if another click comes round while the user is twiddling their thumbs thinking "Show me *now* dammit!". This is just what happens when you do stuff on both click *and* dblclick. Google on two clicks of an event:

![click-dblclick](https://github.com/user-attachments/assets/72ef41f3-a4df-4253-80f2-c50e0c4e93f0)
